//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Indicates that a child has joined or left.
/// Frame value: 0x0023
/// </summary>
public class ChildJoinHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The index of the child of interest.
    /// </summary>
    public byte Index { get; set; }

    /// <summary>
    /// True if the child is joining. False the child is leaving.
    /// </summary>
    public bool Joining { get; set; }

    /// <summary>
    /// The node ID of the child.
    /// </summary>
    public sl_802154_short_addr_t Childid { get; set; }

    /// <summary>
    /// The EUI64 of the child.
    /// </summary>
    public sl_802154_long_addr_t Childeui64 { get; set; }

    /// <summary>
    /// The node type of the child.
    /// </summary>
    public sl_zigbee_node_type_t Childtype { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		ChildJoinHandlerResponse frame = new ChildJoinHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Index = frameBytes[index];
		index += 1;
		frame.Joining = frameBytes[index];
		index += 1;
		frame.Childid = /* TODO: Implement parsing for type sl_802154_short_addr_t */ null;
		index += 0;
		frame.Childeui64 = /* TODO: Implement parsing for type sl_802154_long_addr_t */ null;
		index += 0;
		frame.Childtype = /* TODO: Implement parsing for type sl_zigbee_node_type_t */ null;
		index += 0;

		return frame;
	}
}
