//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Starts periodic many-to-one route discovery. Periodic discovery is started by default on bootup, but this function may be used if discovery has been stopped by a call to ::emberConcentratorStopDiscovery().
/// Frame value: 0x014F
/// </summary>
public class ConcentratorStartDiscoveryResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		ConcentratorStartDiscoveryResponse frame = new ConcentratorStartDiscoveryResponse();
	}
}
}
