//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Obtains the current duty cycle state.
/// Frame value: 0x0035
/// </summary>
public class GetDutyCycleStateResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_status_t value indicating the success or failure of the command.
    /// </summary>
    public sl_status_t status { get; set; }

    /// <summary>
    /// The current duty cycle state in effect.
    /// </summary>
    public sl_zigbee_duty_cycle_state_t returnedState { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GetDutyCycleStateResponse frame = new GetDutyCycleStateResponse();
		frame.status = 		frame.returnedState = 	}
}
}
