//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns the number of cached beacons that have been collected from a scan.
/// Frame value: 0x0008
/// </summary>
public class GetNumStoredBeaconsResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The number of cached beacons that have been collected from a scan.
    /// </summary>
    public byte numBeacons { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GetNumStoredBeaconsResponse frame = new GetNumStoredBeaconsResponse();
		frame.numBeacons = BitConverter.ReadByte();
	}
}
}
