//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

public class GetParentIncomingNwkFrameCounterResponse : EzspFrameResponseV8Plus
{
    public uint parentIncomingNwkFrameCounter { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GetParentIncomingNwkFrameCounterResponse frame = new GetParentIncomingNwkFrameCounterResponse();
		frame.parentIncomingNwkFrameCounter = BitConverter.ReadUInt();
	}
}
}
