//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Gets the channel in use for sending and receiving messages.
/// Frame value: 0x00FF
/// </summary>
public class GetRadioChannelResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Current radio channel.
    /// </summary>
    public byte Channel { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetRadioChannelResponse frame = new GetRadioChannelResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Channel = frameBytes[index];
		index += 1;

		return frame;
	}
}
