//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Gets the routing shortcut threshold used to differentiate between directly using a neighbor vs. performing routing.
/// Frame value: 0x00D1
/// </summary>
public class GetRoutingShortcutThresholdRequest : EzspFrameRequestV8Plus
{
}
