//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Return the maximum number of children for this node. The return value is undefined for nodes that are not joined to a network.
/// Frame value: 0x013C
/// </summary>
public class MaxChildCountResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The maximum number of children.
    /// </summary>
    public byte maxChildCount { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		MaxChildCountResponse frame = new MaxChildCountResponse();
		frame.maxChildCount = BitConverter.ReadByte();
	}
}
}
