//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Return the maximum number of router children for this node. The return value is undefined for nodes that are not joined to a network.
/// Frame value: 0x013D
/// </summary>
public class MaxRouterChildCountRequest : EzspFrameRequestV8Plus
{
}
