//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Reports that a network was found as a result of a prior call to startScan. Gives the network parameters useful for deciding which network to join.
/// Frame value: 0x001B
/// </summary>
public class NetworkFoundHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The parameters associated with the network found.
    /// </summary>
    public sl_zigbee_zigbee_network_t networkFound { get; set; }

    /// <summary>
    /// Link quality of incoming packet from network.
    /// </summary>
    public byte lastHopLqi { get; set; }

    /// <summary>
    /// Power (in dBm) of incoming packet.
    /// </summary>
    public sbyte lastHopRssi { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		NetworkFoundHandlerResponse frame = new NetworkFoundHandlerResponse();
		frame.networkFound = 		frame.lastHopLqi = BitConverter.ReadByte();
		frame.lastHopRssi = BitConverter.ReadSByte();
	}
}
}
