//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Indicate whether a rejoining neighbor should have its incoming frame counter reset.
/// Frame value: 0x0124
/// </summary>
public class ResetRejoiningNeighborsFrameCounterRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Whether or not a neighbor&apos;s incoming FC should be reset upon rejoining (true or false).
    /// </summary>
    public bool reset { get; set; }

}
