//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Return the number of router children that the node currently has.
/// Frame value: 0x013B
/// </summary>
public class RouterChildCountResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The number of router children.
    /// </summary>
    public byte routerChildCount { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		RouterChildCountResponse frame = new RouterChildCountResponse();
		frame.routerChildCount = BitConverter.ReadByte();
	}
}
}
