//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Sets the error code that is sent back from a router with a broken route. 
/// Frame value: 0x0011
/// </summary>
public class SetBrokenRouteErrorCodeResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_status_t value indicating the success or failure of the command.
    /// </summary>
    public sl_status_t status { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		SetBrokenRouteErrorCodeResponse frame = new SetBrokenRouteErrorCodeResponse();
		frame.status = 	}
}
}
