//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Form a new sleepy-to-sleepy network.  If the network is using security, the device must call sli_zigbee_stack_set_initial_security_state() first.
/// Frame value: 0x0119
/// </summary>
public class SleepyToSleepyNetworkStartResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_status_t value indicating success or a reason for failure.
    /// </summary>
    public sl_status_t status { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		SleepyToSleepyNetworkStartResponse frame = new SleepyToSleepyNetworkStartResponse();
		frame.status = 	}
}
}
