#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// Import a transient link key.
/// Frame value: 0x0111
/// </summary>
public class SecManImportTransientKeyRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x0111; } }

    /// <summary>
    /// EUI64 associated with this transient key.
    /// </summary>
	[MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
	public byte[] Eui64;

    /// <summary>
    /// The key to import.
    /// </summary>
	public ZigbeeSecManKey PlaintextKey { get; set; }

}

#endif