#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// Export a transient link key from a given table index.
/// Frame value: 0x0112
/// </summary>
public class SecManExportTransientKeyByIndexRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
	/// </summary>
	public static ushort FrameId { get { return 0x0112; } }

    /// <summary>
    /// Index to export from.
    /// </summary>
	public byte Index { get; set; }

}

#endif