#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// Export the link key associated with the given EUI from the key table.
/// Frame value: 0x010D
/// </summary>
public class SecManExportLinkKeyByEuiRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x010D; } }

    /// <summary>
    /// EUI64 associated with the key to export.
    /// </summary>
	[MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
	public byte[] Eui;

}

#endif