#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// Export a transient link key from a given table index.
/// Frame value: 0x0112
/// </summary>
public class SecManExportTransientKeyByIndexResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Status of key export operation.
    /// </summary>
    public Status Status { get; set; }

    /// <summary>
    /// Context struct for export operation.
    /// </summary>
    public ZigbeeSecManContext Context { get; set; }

    /// <summary>
    /// The exported key.
    /// </summary>
    public ZigbeeSecManKey PlaintextKey { get; set; }

    /// <summary>
    /// Metadata about the key.
    /// </summary>
    public ZigbeeSecManApsKeyMetadata KeyData { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		SecManExportTransientKeyByIndexResponse frame = new SecManExportTransientKeyByIndexResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;
		frame.Context = /* TODO: Implement parsing for type sl_zigbee_sec_man_context_t */ null;
		index += 0;
		frame.PlaintextKey = /* TODO: Implement parsing for type sl_zigbee_sec_man_key_t */ null;
		index += 0;
		frame.KeyData = /* TODO: Implement parsing for type sl_zigbee_sec_man_aps_key_metadata_t */ null;
		index += 0;

		return frame;
	}
}

#endif