#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// This is a callback that indicates the success or failure of an attempt to establish a key with a partner device.
/// Frame value: 0x009B
/// </summary>
public class ZigbeeKeyEstablishmentHandlerRequest : EzspFrameRequestV8Plus
{
}

#endif