#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;
/// <summary>
/// This is a callback that indicates the success or failure of an attempt to establish a key with a partner device.
/// Frame value: 0x009B
/// </summary>
public class ZigbeeKeyEstablishmentHandlerRequest : EzspFrameRequestV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x009B; }

    /// <summary>
    /// Creates the parameters for this frame
    /// </summary>
    /// <returns>The frame parameters as a byte array</returns>
    protected override byte[] CreateParameters()
    {
        return new byte[]
        {
        };
    }
}
#endif