#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Clear a flag to indicate that there are no more messages for a child. The next time the child polls, it will be informed that it does not have any pending messages.
/// Frame value: 0x0137
/// </summary>
public class ClearMessageFlagRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
	/// </summary>
	public static ushort FrameId { get { return 0x0137; } }

    /// <summary>
    /// The ID of the child that no longer has pending messages.
    /// </summary>
	public ushort ChildId { get; set; }

}

#endif