#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Returns the maximum number of no-ack retries that will be attempted
/// Frame value: 0x006A
/// </summary>
public class GetMaxMacRetriesResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Max MAC retries
    /// </summary>
	public byte Retries { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetMaxMacRetriesResponse frame = new GetMaxMacRetriesResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Retries = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif