#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// A callback invoked when a route error message is received. The error indicates that a problem routing to or from the target node was encountered.
/// Frame value: 0x0080
/// </summary>
public class IncomingRouteErrorHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// SL_STATUS_ZIGBEE_SOURCE_ROUTE_FAILURE or SL_STATUS_ZIGBEE_MANY_TO_ONE_ROUTE_FAILURE.
    /// </summary>
    public sl_status_t Status { get; set; }

    /// <summary>
    /// The short id of the remote node.
    /// </summary>
    public ushort Target { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		IncomingRouteErrorHandlerResponse frame = new IncomingRouteErrorHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;
		frame.Target = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;

		return frame;
	}
}

#endif