#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Reports the arrival of a route record command frame.
/// Frame value: 0x0059
/// </summary>
public class IncomingRouteRecordHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The source of the route record.
    /// </summary>
    public ushort Source { get; set; }

    /// <summary>
    /// The EUI64 of the source.
    /// </summary>
    public byte Sourceeui { get; set; }

    /// <summary>
    /// The link quality from the node that last relayed the route record.
    /// </summary>
    public byte Lasthoplqi { get; set; }

    /// <summary>
    /// The energy level (in units of dBm) observed during the reception.
    /// </summary>
    public sbyte Lasthoprssi { get; set; }

    /// <summary>
    /// The number of relays in &lt;i&gt;relayList&lt;/i&gt;.
    /// </summary>
    public byte Relaycount { get; set; }

    /// <summary>
    /// The route record. Each relay in the list is an uint16_t node ID. The list is passed as uint8_t * to avoid alignment problems.
    /// </summary>
    public Uint8TRelaycount2 Relaylist { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		IncomingRouteRecordHandlerResponse frame = new IncomingRouteRecordHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Source = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;
		frame.Sourceeui = frameBytes[index];
		index += 1;
		frame.Lasthoplqi = frameBytes[index];
		index += 1;
		frame.Lasthoprssi = frameBytes[index];
		index += 1;
		frame.Relaycount = frameBytes[index];
		index += 1;
		frame.Relaylist = /* TODO: Implement parsing for type uint8_t[relayCount*2] */ null;
		index += 0;

		return frame;
	}
}

#endif