#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Returns the node ID that corresponds to the specified EUI64. The node ID is found by searching through all stack tables for the specified EUI64.
/// Frame value: 0x0060
/// </summary>
public class LookupNodeIdByEui64Response : EzspFrameResponseV8Plus
{
    /// <summary>
    /// SL_STATUS_OK if the short ID was found, SL_STATUS_FAIL if the short ID is not known.
    /// </summary>
    public sl_status_t Status { get; set; }

    /// <summary>
    /// The short ID of the node or SL_ZIGBEE_NULL_NODE_ID if the short ID is not known.
    /// </summary>
    public ushort Nodeid { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		LookupNodeIdByEui64Response frame = new LookupNodeIdByEui64Response();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;
		frame.Nodeid = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;

		return frame;
	}
}

#endif