#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Indicates that the local node received a data poll from a child.
/// Frame value: 0x0044
/// </summary>
public class PollHandlerResponse : EzspFrameResponseV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x0044; } }

    /// <summary>
    /// The node ID of the child that is requesting data.
    /// </summary>
	public ushort ChildId { get; set; }

    /// <summary>
    /// True if transmit is expected, false otherwise.
    /// </summary>
	public bool TransmitExpected { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		PollHandlerResponse frame = new PollHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.ChildId = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;
		frame.TransmitExpected = ((frameBytes[index] & 1) == 1);
		index += 1;

		return frame;
	}
}

#endif