#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Set the network update ID to the desired value. Must be called before joining or forming the network.
/// Frame value: 0x011D
/// </summary>
public class SetNwkUpdateIdRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x011D; } }

    /// <summary>
    /// Desired value of the network update ID.
    /// </summary>
	public byte NwkUpdateId { get; set; }

    /// <summary>
    /// Set to true in case change should also apply when on network.
    /// </summary>
	public bool SetWhenOnNetwork { get; set; }

}

#endif