#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Sets source route discovery(MTORR) mode to on, off, reschedule
/// Frame value: 0x005A
/// </summary>
public class SetSourceRouteDiscoveryModeRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Source route discovery mode: off:0, on:1, reschedule:2
    /// </summary>
    public byte mode { get; set; }

}

#endif