//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Mfglib.Frames;

/// <summary>
/// Returns the current radio channel, as previously set via mfglibInternalSetChannel().
/// Frame value: 0x008b
/// </summary>
public class MfglibInternalGetChannelRequest : EzspFrameRequestV8Plus
{
}
