#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Convert a node ID to a child index
/// Frame value: 0x0107
/// </summary>
public class ChildIndexResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The child index or 0xFF if the node ID doesn&apos;t belong to a child
    /// </summary>
    public byte ChildIndex { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		ChildIndexResponse frame = new ChildIndexResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.ChildIndex = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif