#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Forms a new network by becoming the coordinator.
/// Frame value: 0x001E
/// </summary>
public class FormNetworkRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Specification of the new network.
    /// </summary>
    public ZigbeeNetworkParameters parameters { get; set; }

}

#endif