#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns the neighbor table entry at the given index. The number of active neighbors can be obtained using the neighborCount command.
/// Frame value: 0x0079
/// </summary>
public class GetNeighborResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// SL_STATUS_FAIL if the index is greater or equal to the number of active neighbors, or if the device is an end device. Returns SL_STATUS_OK otherwise.
    /// </summary>
    public Status Status { get; set; }

    /// <summary>
    /// The contents of the neighbor table entry.
    /// </summary>
    public ZigbeeNeighborTableEntry Value { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetNeighborResponse frame = new GetNeighborResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = (Status)BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
		index += 4;
		frame.Value = MemoryMarshal.Read<ZigbeeNeighborTableEntry>(frameBytes.Slice(index, 14));
		index += 14;

		return frame;
	}
}

#endif