#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns information about the children of the local node and the parent of the local node.
/// Frame value: 0x0029
/// </summary>
public class GetParentChildParametersResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The number of children the node currently has.
    /// </summary>
    public byte Childcount { get; set; }

    /// <summary>
    /// The parent&apos;s EUI64. The value is undefined for nodes without parents (coordinators and nodes that are not joined to a network).
    /// </summary>
    public byte Parenteui64 { get; set; }

    /// <summary>
    /// The parent&apos;s node ID. The value is undefined for nodes without parents (coordinators and nodes that are not joined to a network).
    /// </summary>
    public ushort Parentnodeid { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetParentChildParametersResponse frame = new GetParentChildParametersResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Childcount = frameBytes[index];
		index += 1;
		frame.Parenteui64 = frameBytes[index];
		index += 1;
		frame.Parentnodeid = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;

		return frame;
	}
}

#endif