#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns the route table entry at the given index. The route table size can be obtained using the getConfigurationValue command.
/// Frame value: 0x007B
/// </summary>
public class GetRouteTableEntryResponse : EzspFrameResponseV8Plus
{
	/// <summary>
	/// The frameId of the frame
	/// </summary>
	public static ushort FrameId { get { return 0x007B; } }

    /// <summary>
    /// SL_STATUS_FAIL if the index is out of range or the device is an end device, and SL_STATUS_OK otherwise.
    /// </summary>
	public Status Status { get; set; }

    /// <summary>
    /// The contents of the route table entry.
    /// </summary>
	public ZigbeeRouteTableEntry Value { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetRouteTableEntryResponse frame = new GetRouteTableEntryResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = (Status)BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
		index += 4;
		frame.Value = MemoryMarshal.Read<ZigbeeRouteTableEntry>(frameBytes.Slice(index, 8));
		index += 8;

		return frame;
	}
}

#endif