#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns the source route table total size.
/// Frame value: 0x00C3
/// </summary>
public class GetSourceRouteTableTotalSizeResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Total size of source route table.
    /// </summary>
	public byte SourceRouteTableTotalSize { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetSourceRouteTableTotalSizeResponse frame = new GetSourceRouteTableTotalSizeResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.SourceRouteTableTotalSize = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif