#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Fetches the specified beacon in the cache. Beacons are stored in cache after issuing an active scan.
/// Frame value: 0x0004
/// </summary>
public class GetStoredBeaconRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// The beacon index to fetch. Valid values range from 0 to &lt;i&gt;sli_zigbee_stack_get_num_stored_beacons&lt;/i&gt;-1.
    /// </summary>
	public byte BeaconNumber { get; set; }

}

#endif