#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Check whether a rejoining neighbor will have its incoming frame counter reset based on the currently set policy.
/// Frame value: 0x0125
/// </summary>
public class IsResetRejoiningNeighborsFrameCounterEnabledRequest : EzspFrameRequestV8Plus
{
}

#endif