#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns the number of active entries in the neighbor table.
/// Frame value: 0x007A
/// </summary>
public class NeighborCountResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The number of active entries in the neighbor table.
    /// </summary>
	public byte Value { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		NeighborCountResponse frame = new NeighborCountResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Value = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif