#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Returns a value indicating whether the node is joining, joined to, or leaving a network.
/// Frame value: 0x0018
/// </summary>
public class NetworkStateResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_zigbee_network_status_t value indicating the current join status.
    /// </summary>
    public ZigbeeNetworkStatus Status { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		NetworkStateResponse frame = new NetworkStateResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_zigbee_network_status_t */ null;
		index += 0;

		return frame;
	}
}

#endif