#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;
/// <summary>
/// Indicate whether the stack is currently in a state where there are no high-priority tasks, allowing the device to sleep.
/// There may be tasks expecting incoming messages, in which case the device should periodically wake up and call ::emberPollForData() in order to receive messages. This function can only be called when the node type is ::SL_ZIGBEE_SLEEPY_END_DEVICE
/// Frame value: 0x0146
/// </summary>
public class OkToNapResponse : EzspFrameResponseV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x0146; }
    /// <summary>
    /// True if the application may sleep but the stack may be expecting incoming messages.
    /// </summary>
    public bool Value { get; set; }

    public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
    {
        OkToNapResponse frame = new OkToNapResponse();
        int index = frame.ParseHeader(frameBytes);
        frame.Value = (frameBytes[index] & 1) == 1;
        index += 1;
        return frame;
    }
}
#endif