#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// Send a Zigbee NWK Leave command to the destination.
/// Frame value: 0x011A
/// </summary>
public class SendZigbeeLeaveRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
	/// </summary>
	public static ushort FrameId { get { return 0x011A; } }

    /// <summary>
    /// Node ID of the device being told to leave.
    /// </summary>
	public ushort Destination { get; set; }

    /// <summary>
    /// Bitmask indicating additional considerations for the leave request.
    /// </summary>
	public ZigbeeLeaveRequestFlags Flags { get; set; }

}

#endif