#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;
/// <summary>
/// Sets child data to the child table token.
/// Frame value: 0x00AC
/// </summary>
public class SetChildDataResponse : EzspFrameResponseV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x00AC; }
    /// <summary>
    /// SL_STATUS_OK if the child data is set successfully at &lt;i&gt;index&lt;/i&gt;. SL_STATUS_INVALID_INDEX if provided &lt;i&gt;index&lt;/i&gt; is out of range.
    /// </summary>
    public Status Status { get; set; }

    public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
    {
        SetChildDataResponse frame = new SetChildDataResponse();
        int index = frame.ParseHeader(frameBytes);
        frame.Status = (Status)BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
        index += 4;
        return frame;
    }
}
#endif