#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;

/// <summary>
/// This function returns an unused panID and channel pair found via the find unused panId scan procedure.
/// Frame value: 0x00D2
/// </summary>
public class UnusedPanIdFoundHandlerRequest : EzspFrameRequestV8Plus
{
}

#endif