#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Networking.Frames;
/// <summary>
/// This function returns an unused panID and channel pair found via the find unused panId scan procedure.
/// Frame value: 0x00D2
/// </summary>
public class UnusedPanIdFoundHandlerResponse : EzspFrameResponseV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x00D2; }
    /// <summary>
    /// The unused panID which has been found.
    /// </summary>
    public ushort PanId { get; set; }
    /// <summary>
    /// The channel that the unused panID was found on.
    /// </summary>
    public byte Channel { get; set; }

    public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
    {
        EmberResponseHeader header = EzspFrameResponseV8Plus.ParseHeader(frameBytes);
        UnusedPanIdFoundHandlerResponse frame = new UnusedPanIdFoundHandlerResponse();
        int index = Constants.EmberFrameHeaderLength;
        frame.PanId = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
        index += 2;
        frame.Channel = frameBytes[index];
        index += 1;
        return frame;
    }
}
#endif