//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Returns the 16-bit node ID of the local node.
/// Frame value: 0x0027
/// </summary>
public class GetNodeIdResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The 16-bit ID.
    /// </summary>
    public ushort Nodeid { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetNodeIdResponse frame = new GetNodeIdResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Nodeid = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;

		return frame;
	}
}
