//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Get the current multiprotocol sliptime
/// Frame value: 0x012C
/// </summary>
public class RadioGetSchedulerSliptimeResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Value of the current slip time.
    /// </summary>
    public uint32_t[1] slipTime { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		RadioGetSchedulerSliptimeResponse frame = new RadioGetSchedulerSliptimeResponse();
		frame.slipTime = 	}
}
}
