//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Get the current scheduler priorities for radio operations
/// Frame value: 0x012A
/// </summary>
public class RadioGetSchedulerPrioritiesResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The current priorities.
    /// </summary>
    public sl_802154_radio_priorities_t Priorities { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		RadioGetSchedulerPrioritiesResponse frame = new RadioGetSchedulerPrioritiesResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Priorities = /* TODO: Implement parsing for type sl_802154_radio_priorities_t */ null;
		index += 0;

		return frame;
	}
}
