//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Retrieves and clears Ember counters. See the sl_zigbee_counter_type_t enumeration for the counter types.
/// Frame value: 0x0065
/// </summary>
public class ReadAndClearCountersResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// A list of all counter values ordered according to the sl_zigbee_counter_type_t enumeration.
    /// </summary>
    public uint16_t[SL_ZIGBEE_COUNTER_TYPE_COUNT] values { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		ReadAndClearCountersResponse frame = new ReadAndClearCountersResponse();
		frame.values = 	}
}
}
