#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// Set the secondary ZLL (touchlink) channel mask.
/// Frame value: 0x00DC
/// </summary>
public class SetZllSecondaryChannelMaskResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		SetZllSecondaryChannelMaskResponse frame = new SetZllSecondaryChannelMaskResponse();
		int index = frame.ParseHeader(frameBytes);


		return frame;
	}
}

#endif