#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// This call is fired when network and group addresses are assigned to a remote mode in a network start or network join request.
/// Frame value: 0x00B8
/// </summary>
public class ZllAddressAssignmentHandlerRequest : EzspFrameRequestV8Plus
{
}

#endif