#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// This call is fired when a ZLL network scan finds a ZLL network.
/// Frame value: 0x00B6
/// </summary>
public class ZllNetworkFoundHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Information about the network.
    /// </summary>
    public ZigbeeZllNetwork Networkinfo { get; set; }

    /// <summary>
    /// Used to interpret deviceInfo field.
    /// </summary>
    public bool Isdeviceinfonull { get; set; }

    /// <summary>
    /// Device specific information.
    /// </summary>
    public ZigbeeZllDeviceInfoRecord Deviceinfo { get; set; }

    /// <summary>
    /// Information about the incoming packet received from this network.
    /// </summary>
    public ZigbeeRxPacketInfo Packetinfo { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		ZllNetworkFoundHandlerResponse frame = new ZllNetworkFoundHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Networkinfo = /* TODO: Implement parsing for type sl_zigbee_zll_network_t */ null;
		index += 0;
		frame.Isdeviceinfonull = frameBytes[index];
		index += 1;
		frame.Deviceinfo = /* TODO: Implement parsing for type sl_zigbee_zll_device_info_record_t */ null;
		index += 0;
		frame.Packetinfo = /* TODO: Implement parsing for type sl_zigbee_rx_packet_info_t */ null;
		index += 0;

		return frame;
	}
}

#endif