#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// This call is fired when a ZLL network scan finds a ZLL network.
/// Frame value: 0x00B6
/// </summary>
public class ZllNetworkFoundHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Information about the network.
    /// </summary>
    public ZigbeeZllNetwork Networkinfo { get; set; }

    /// <summary>
    /// Used to interpret deviceInfo field.
    /// </summary>
    public bool Isdeviceinfonull { get; set; }

    /// <summary>
    /// Device specific information.
    /// </summary>
    public ZigbeeZllDeviceInfoRecord Deviceinfo { get; set; }

    /// <summary>
    /// Information about the incoming packet received from this network.
    /// </summary>
    public ZigbeeRxPacketInfo Packetinfo { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		ZllNetworkFoundHandlerResponse frame = new ZllNetworkFoundHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Networkinfo = MemoryMarshal.Read<ZigbeeZllNetwork>(frameBytes.Slice(index, 40));
		index += 40;
		frame.Isdeviceinfonull = ((frameBytes[index] & 1) == 1);
		index += 1;
		frame.Deviceinfo = MemoryMarshal.Read<ZigbeeZllDeviceInfoRecord>(frameBytes.Slice(index, 15));
		index += 15;
		frame.Packetinfo = MemoryMarshal.Read<ZigbeeRxPacketInfo>(frameBytes.Slice(index, 18));
		index += 18;

		return frame;
	}
}

#endif