#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// A consolidation of ZLL network operations with similar signatures; specifically, forming and joining networks or touch-linking.
/// Frame value: 0x00B2
/// </summary>
public class ZllNetworkOpsRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Information about the network.
    /// </summary>
    public ZigbeeZllNetwork networkInfo { get; set; }

    /// <summary>
    /// Operation indicator.
    /// </summary>
    public ZigbeeEzspZllNetworkOperation op { get; set; }

    /// <summary>
    /// Radio transmission power.
    /// </summary>
    public sbyte radioTxPower { get; set; }

}

#endif