#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// This call will cause the device to setup the security information used in its network. It must be called prior to forming, starting, or joining a network.
/// Frame value: 0x00B3
/// </summary>
public class ZllSetInitialSecurityStateResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_status_t value indicating success or the reason for failure.
    /// </summary>
	public Status Status { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		ZllSetInitialSecurityStateResponse frame = new ZllSetInitialSecurityStateResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = (Status)BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
		index += 4;

		return frame;
	}
}

#endif