using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models.TypeMapper;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Services;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Utility;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace ZigBeeNet.EmberV8Plus.CodeGenerator.Parser
{
    /// <summary>
    /// Generates frame request and response classes using Roslyn syntax trees.
    /// </summary>
    internal class FrameDefinitionGenerator
    {
        private readonly CSharpLanguageService _textService;
        private readonly TypeMapperService _typeMapperService;
        private readonly CodeGenerator _codeGenerator;

        public FrameDefinitionGenerator(CSharpLanguageService textService, TypeMapperService typeMapperService)
        {
            _textService = textService;
            _typeMapperService = typeMapperService;
            _codeGenerator = new CodeGenerator(textService, typeMapperService);
        }

        /// <summary>
        /// Generates a frame request class for a given frame definition.
        /// </summary>
        public CompilationUnitSyntax GenerateFrameRequestClass(string sectionName, FrameDefinition frameDefinition)
        {
            string sanitizedSectionName = Sanitize.SectionName(sectionName);
            string className = Sanitize.FunctionName(frameDefinition.CommandName) + "Request";

            // Create using statements
            var usings = new[]
            {
                UsingDirective(ParseName("System")),
                UsingDirective(ParseName("System.Buffers.Binary")),
                UsingDirective(ParseName("System.Collections.Generic")),
                UsingDirective(ParseName("System.Runtime.InteropServices")),
                UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp")),
                UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations")),
                UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types")),
            };

            // Add section-specific types namespace if needed
            var usingsList = usings.ToList();
            if (_typeMapperService.SectionTypeMappingExists(sanitizedSectionName))
            {
                usingsList.Add(UsingDirective(ParseName($"ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Types")));
            }

            // Create class members
            var classMembers = new List<MemberDeclarationSyntax>();

            // Add FrameId property
            classMembers.Add(GenerateFrameIdProperty(frameDefinition.Value));

            // Add command argument properties
            if (frameDefinition.CommandArguments != null && frameDefinition.CommandArguments.Count > 0)
            {
                foreach (var arg in frameDefinition.CommandArguments)
                {
                    classMembers.Add(GeneratePropertyForArgument(arg));
                }
            }

            // Add CreateParameters method
            classMembers.Add(GenerateCreateParametersMethod());

            // Create class declaration
            var classDeclaration = ClassDeclaration(className)
                .AddModifiers(Token(SyntaxKind.PublicKeyword))
                .AddBaseListTypes(
                    SimpleBaseType(ParseTypeName("EzspFrameRequestV8Plus")),
                    SimpleBaseType(ParseTypeName("IFrameIdentifier")))
                .AddMembers(classMembers.ToArray())
                .WithLeadingTrivia(_codeGenerator.GenerateClassXmlDocumentation(frameDefinition));

            // Create file-scoped namespace declaration
            var namespaceDeclaration = FileScopedNamespaceDeclaration(ParseName($"ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Frames"))
                .AddMembers(classDeclaration);

            // Create compilation unit with autogenerated header
            return CompilationUnit()
                .AddUsings(usingsList.ToArray())
                .AddMembers(namespaceDeclaration)
                .NormalizeWhitespace()
                .WithLeadingTrivia(_codeGenerator.GenerateAutoGeneratedHeaderTrivia());
        }

        /// <summary>
        /// Generates a frame response class for a given frame definition.
        /// </summary>
        public CompilationUnitSyntax GenerateFrameResponseClass(string sectionName, FrameDefinition frameDefinition)
        {
            string sanitizedSectionName = Sanitize.SectionName(sectionName);
            string className = Sanitize.FunctionName(frameDefinition.CommandName) + "Response";

            // Create using statements
            var usings = new[]
            {
                UsingDirective(ParseName("System")),
                UsingDirective(ParseName("System.Buffers.Binary")),
                UsingDirective(ParseName("System.Collections.Generic")),
                UsingDirective(ParseName("System.Runtime.InteropServices")),
                UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp")),
                UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations")),
                UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types")),
				UsingDirective(ParseName("ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Types")),
            };

            // Add section-specific types namespace if needed
            var usingsList = usings.ToList();
            if (_typeMapperService.SectionTypeMappingExists(sanitizedSectionName))
            {
                usingsList.Add(UsingDirective(ParseName($"ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Types")));
            }

            // Create class members
            var classMembers = new List<MemberDeclarationSyntax>();

            // Add FrameId property
            classMembers.Add(GenerateFrameIdProperty(frameDefinition.Value));

            // Add response argument properties
            if (frameDefinition.ResponseArguments != null && frameDefinition.ResponseArguments.Count > 0)
            {
                foreach (var arg in frameDefinition.ResponseArguments)
                {
                    classMembers.Add(GeneratePropertyForArgument(arg));
                }
            }

            // Add Parse method
            classMembers.Add(GenerateParseMethod(className, frameDefinition));

            // Create class declaration
            var classDeclaration = ClassDeclaration(className)
                .AddModifiers(Token(SyntaxKind.PublicKeyword))
                .AddBaseListTypes(
                    SimpleBaseType(ParseTypeName("EzspFrameResponseV8Plus")),
                    SimpleBaseType(ParseTypeName("IFrameIdentifier")))
                .AddMembers(classMembers.ToArray())
                .WithLeadingTrivia(_codeGenerator.GenerateClassXmlDocumentation(frameDefinition));

            // Create file-scoped namespace declaration
            var namespaceDeclaration = FileScopedNamespaceDeclaration(ParseName($"ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Frames"))
                .AddMembers(classDeclaration);

            // Create compilation unit with autogenerated header
            return CompilationUnit()
                .AddUsings(usingsList.ToArray())
                .AddMembers(namespaceDeclaration)
                .NormalizeWhitespace()
                .WithLeadingTrivia(_codeGenerator.GenerateAutoGeneratedHeaderTrivia());
        }

        private PropertyDeclarationSyntax GenerateFrameIdProperty(string frameValue)
        {
            return PropertyDeclaration(ParseTypeName("ushort"), "FrameId")
                .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
                .AddAccessorListAccessors(
                    AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithExpressionBody(ArrowExpressionClause(ParseExpression(frameValue)))
                        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))
                .WithLeadingTrivia(TriviaList(
                    Comment("/// <summary>"),
                    Comment("/// The frameId of the frame"),
                    Comment("/// </summary>")));
        }

        private MethodDeclarationSyntax GenerateCreateParametersMethod()
        {
            return MethodDeclaration(ParseTypeName("byte[]"), "CreateParameters")
                .AddModifiers(Token(SyntaxKind.ProtectedKeyword), Token(SyntaxKind.OverrideKeyword))
                .WithBody(Block(
                    ReturnStatement(
                        ArrayCreationExpression(ArrayType(ParseTypeName("byte"))
                            .AddRankSpecifiers(ArrayRankSpecifier()))
                        .WithInitializer(InitializerExpression(SyntaxKind.ArrayInitializerExpression)))))
                .WithLeadingTrivia(TriviaList(
                    Comment("/// <summary>"),
                    Comment("/// Creates the parameters for this frame"),
                    Comment("/// </summary>"),
                    Comment("/// <returns>The frame parameters as a byte array</returns>")));
        }

        private MemberDeclarationSyntax GeneratePropertyForArgument(FrameArgument arg)
        {
            var propertyName = arg.Name.AsPropertyName();

            // Check if the type contains array notation (e.g., "byte[16]")
            int typeBracketIndex = arg.Type?.IndexOf('[') ?? -1;
            if (typeBracketIndex >= 0)
            {
                // Extract base type and array size from type string
                string fieldArrayType = arg.Type![..typeBracketIndex];
                string arrayPart = arg.Type[typeBracketIndex..];
                string arraySize = arrayPart.Trim('[', ']');
                TypeMapping? csharpBaseType = _typeMapperService.GetTypeMapping(fieldArrayType);

                // Check if array size is numeric (compile-time constant)
                if (int.TryParse(arraySize, out int numericSize))
                {
                    // Fixed-size array with numeric constant
                    var marshalAttribute = Attribute(IdentifierName("MarshalAs"))
                        .AddArgumentListArguments(
                            AttributeArgument(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("UnmanagedType"),
                                IdentifierName("ByValArray"))),
                            AttributeArgument(AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                IdentifierName("SizeConst"),
                                LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(numericSize)))));

                    return FieldDeclaration(
                        VariableDeclaration(ArrayType(ParseTypeName(csharpBaseType?.CSharpType.Name ?? "byte"))
                            .AddRankSpecifiers(ArrayRankSpecifier()))
                        .AddVariables(VariableDeclarator(Identifier(propertyName))))
                    .AddModifiers(Token(SyntaxKind.PublicKeyword))
                    .AddAttributeLists(AttributeList(SeparatedList(new[] { marshalAttribute })))
                    .WithLeadingTrivia(_codeGenerator.GeneratePropertyXmlDocumentation(arg));
                }
                else
                {
                    // Symbolic array size - try to map it to a constant
                    string mappedConstant = MapCConstants.MapConstant(arraySize);
                    if (!string.IsNullOrEmpty(mappedConstant) && int.TryParse(mappedConstant, out int symbolicSize))
                    {
                        var marshalAttribute = Attribute(IdentifierName("MarshalAs"))
                            .AddArgumentListArguments(
                                AttributeArgument(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName("UnmanagedType"),
                                    IdentifierName("ByValArray"))),
                                AttributeArgument(AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName("SizeConst"),
                                    LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(symbolicSize)))));

                        return FieldDeclaration(
                            VariableDeclaration(ArrayType(ParseTypeName(csharpBaseType?.CSharpType.Name ?? "byte"))
                                .AddRankSpecifiers(ArrayRankSpecifier()))
                            .AddVariables(VariableDeclarator(Identifier(propertyName))))
                        .AddModifiers(Token(SyntaxKind.PublicKeyword))
                        .AddAttributeLists(AttributeList(SeparatedList(new[] { marshalAttribute })))
                        .WithLeadingTrivia(_codeGenerator.GeneratePropertyXmlDocumentation(arg));
                    }
                    else
                    {
                        // Symbolic size without mapping - just create array field without MarshalAs
                        return FieldDeclaration(
                            VariableDeclaration(ArrayType(ParseTypeName(csharpBaseType?.CSharpType.Name ?? "byte"))
                                .AddRankSpecifiers(ArrayRankSpecifier()))
                            .AddVariables(VariableDeclarator(Identifier(propertyName))))
                        .AddModifiers(Token(SyntaxKind.PublicKeyword))
                        .WithLeadingTrivia(_codeGenerator.GeneratePropertyXmlDocumentation(arg));
                    }
                }
            }
            else
            {
                // No array notation in type string - check if the mapped type is an array
                var typeMapping = _typeMapperService.GetTypeMapping(arg.Type);

                if (typeMapping?.CSharpType.IsArray == true)
                {
                    // Mapped type is an array - add MarshalAs attribute
                    var marshalAttribute = Attribute(IdentifierName("MarshalAs"))
                        .AddArgumentListArguments(
                            AttributeArgument(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("UnmanagedType"),
                                IdentifierName("ByValArray"))),
                            AttributeArgument(AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                IdentifierName("SizeConst"),
                                LiteralExpression(SyntaxKind.NumericLiteralExpression,
                                    Literal(typeMapping?.CSharpType.ArrayLength ?? 0)))));

                    return FieldDeclaration(
                        VariableDeclaration(ArrayType(ParseTypeName(typeMapping?.CSharpType.Name ?? "byte"))
                            .AddRankSpecifiers(ArrayRankSpecifier()))
                        .AddVariables(VariableDeclarator(Identifier(propertyName))))
                    .AddModifiers(Token(SyntaxKind.PublicKeyword))
                    .AddAttributeLists(AttributeList(SeparatedList(new[] { marshalAttribute })))
                    .WithLeadingTrivia(_codeGenerator.GeneratePropertyXmlDocumentation(arg));
                }
                else
                {
                    // Non-array type - create auto-property
                    return PropertyDeclaration(ParseTypeName(typeMapping?.CSharpType.Name ?? "object"), propertyName)
                        .AddModifiers(Token(SyntaxKind.PublicKeyword))
                        .AddAccessorListAccessors(
                            AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                            AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))
                        .WithLeadingTrivia(_codeGenerator.GeneratePropertyXmlDocumentation(arg));
                }
            }
        }

        private MethodDeclarationSyntax GenerateParseMethod(string className, FrameDefinition frameDefinition)
        {
            var statements = new List<StatementSyntax>();

            // EmberResponseHeader header = EzspFrameResponseV8Plus.ParseHeader(frameBytes);
            statements.Add(LocalDeclarationStatement(
                VariableDeclaration(ParseTypeName("EmberResponseHeader"))
                    .AddVariables(VariableDeclarator(Identifier("header"))
                        .WithInitializer(EqualsValueClause(
                            InvocationExpression(
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName("EzspFrameResponseV8Plus"),
                                    IdentifierName("ParseHeader")))
                            .AddArgumentListArguments(Argument(IdentifierName("frameBytes"))))))));

            // frame = new ClassName();
            statements.Add(LocalDeclarationStatement(
                VariableDeclaration(ParseTypeName(className))
                    .AddVariables(VariableDeclarator(Identifier("frame"))
                        .WithInitializer(EqualsValueClause(
                            ObjectCreationExpression(ParseTypeName(className))
                                .WithArgumentList(ArgumentList()))))));

            // int index = Constants.EmberFrameHeaderLength;
            statements.Add(LocalDeclarationStatement(
                VariableDeclaration(ParseTypeName("int"))
                    .AddVariables(VariableDeclarator(Identifier("index"))
                        .WithInitializer(EqualsValueClause(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("Constants"),
                                IdentifierName("EmberFrameHeaderLength")))))));

            // Parse response arguments
            if (frameDefinition.ResponseArguments != null && frameDefinition.ResponseArguments.Count > 0)
            {
                foreach (var arg in frameDefinition.ResponseArguments)
                {
                    statements.AddRange(GenerateParseArgumentStatements(arg));
                }
            }

            // return frame;
            statements.Add(ReturnStatement(IdentifierName("frame")));

            return MethodDeclaration(ParseTypeName("EzspFrameResponseV8Plus"), "Parse")
                .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
                .AddParameterListParameters(
                    Parameter(Identifier("frameBytes"))
                        .WithType(ParseTypeName("ReadOnlySpan<byte>")))
                .WithBody(Block(statements));
        }

        private List<StatementSyntax> GenerateParseArgumentStatements(FrameArgument arg)
        {
            var statements = new List<StatementSyntax>();
            var propertyName = arg.Name.AsPropertyName();

            // Check if this is an array type
            if (arg.Type.IsArrayTypeDefinition() == true)
            {
                var baseType = arg.Type.GetArrayDefinitionBaseType();
                var typeMapping = _typeMapperService.GetTypeMapping(baseType);
                int arraySize = arg.Type.GetArrayDefinitionSize();
                string arrayLengthSymbolicSize = string.Empty;

                // If we have a symbolic size, try to map it to a constant
                if (arraySize == -1)
                {
                    arrayLengthSymbolicSize = arg.Type.GetArrayDefinitionSymbolicSize();
                    if (!string.IsNullOrEmpty(MapCConstants.MapConstant(arrayLengthSymbolicSize)))
                    {
                        arraySize = int.Parse(MapCConstants.MapConstant(arrayLengthSymbolicSize));
                    }
                }

                bool isVariableLengthArray = arraySize == -1;

                if (typeMapping?.CSharpType.Name == "byte" && isVariableLengthArray == true)
                {
                    // frame.fieldName = frameBytes.Slice(index, frame.symbolicSize).ToArray();
                    statements.Add(ExpressionStatement(
                        AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frame"),
                                IdentifierName(propertyName)),
                            InvocationExpression(
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    InvocationExpression(
                                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                            IdentifierName("frameBytes"),
                                            IdentifierName("Slice")))
                                    .AddArgumentListArguments(
                                        Argument(IdentifierName("index")),
                                        Argument(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                            IdentifierName("frame"),
                                            IdentifierName(arrayLengthSymbolicSize.AsPropertyName())))),
                                    IdentifierName("ToArray")))
                            .WithArgumentList(ArgumentList()))));

                    // index += frame.symbolicSize;
                    statements.Add(ExpressionStatement(
                        AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                            IdentifierName("index"),
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frame"),
                                IdentifierName(arrayLengthSymbolicSize.AsPropertyName())))));
                }
                else if (isVariableLengthArray == false && typeMapping != null)
                {
                    // Fixed-size array: MemoryMarshal.Cast<byte, T>(frameBytes.Slice(index, size)).ToArray();
                    int totalBytes = (int)typeMapping?.CType.SizeInBytes * arraySize;
                    statements.Add(ExpressionStatement(
                        AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frame"),
                                IdentifierName(propertyName)),
                            InvocationExpression(
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    InvocationExpression(
                                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                            IdentifierName("MemoryMarshal"),
                                            GenericName("Cast")
                                                .AddTypeArgumentListArguments(
                                                    ParseTypeName("byte"),
                                                    ParseTypeName(typeMapping?.CSharpType.Name))))
                                    .AddArgumentListArguments(
                                        Argument(InvocationExpression(
                                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("frameBytes"),
                                                IdentifierName("Slice")))
                                            .AddArgumentListArguments(
                                                Argument(IdentifierName("index")),
                                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression,
                                                    Literal(totalBytes)))))),
                                    IdentifierName("ToArray")))
                            .WithArgumentList(ArgumentList()))));

                    // index += totalBytes;
                    statements.Add(ExpressionStatement(
                        AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                            IdentifierName("index"),
                            LiteralExpression(SyntaxKind.NumericLiteralExpression,
                                Literal(totalBytes)))));
                }
            }
            else
            {
                // Non-array type
                var typeMapping = _typeMapperService.GetTypeMapping(arg.Type);

                if (typeMapping != null)
                {
                    if (typeMapping?.CType.IsEnum == true)
                    {
                        // Enum: frame.field = (EnumType)ReadPrimitive(baseType);
                        var baseTypeMapping = _typeMapperService.GetTypeMapping(typeMapping?.CType.UnderlyingTypeName ?? "");
                        if (baseTypeMapping != null)
                        {
                            statements.Add(ExpressionStatement(
                                AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName("frame"),
                                        IdentifierName(propertyName)),
                                    CastExpression(ParseTypeName(typeMapping?.CSharpType.Name),
                                        GenerateReadPrimitiveExpression(baseTypeMapping?.CSharpType.Name)))));
                        }
                    }
                    else if (typeMapping?.CType.IsStruct == true)
                    {
                        // Struct: frame.field = MemoryMarshal.Read<StructType>(frameBytes.Slice(index, size));
                        statements.Add(ExpressionStatement(
                            AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName("frame"),
                                    IdentifierName(propertyName)),
                                InvocationExpression(
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName("MemoryMarshal"),
                                        GenericName("Read")
                                            .AddTypeArgumentListArguments(
                                                ParseTypeName(typeMapping?.CSharpType.Name))))
                                .AddArgumentListArguments(
                                    Argument(InvocationExpression(
                                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                            IdentifierName("frameBytes"),
                                            IdentifierName("Slice")))
                                        .AddArgumentListArguments(
                                            Argument(IdentifierName("index")),
                                            Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression,
                                                Literal((int)typeMapping?.CType.SizeInBytes)))))))));
                    }
                    else if (typeMapping?.CSharpType.IsArray == true)
                    {
                        // Array type: frame.field = frameBytes.Slice(index, size).ToArray();
                        statements.Add(ExpressionStatement(
                            AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName("frame"),
                                    IdentifierName(propertyName)),
                                InvocationExpression(
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        InvocationExpression(
                                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("frameBytes"),
                                                IdentifierName("Slice")))
                                        .AddArgumentListArguments(
                                            Argument(IdentifierName("index")),
                                            Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression,
                                                Literal((int)typeMapping?.CType.SizeInBytes)))),
                                        IdentifierName("ToArray")))
                                .WithArgumentList(ArgumentList()))));
                    }
                    else
                    {
                        // Primitive type: frame.field = ReadPrimitive(type);
                        statements.Add(ExpressionStatement(
                            AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName("frame"),
                                    IdentifierName(propertyName)),
                                GenerateReadPrimitiveExpression(typeMapping?.CSharpType.Name))));
                    }

                    // index += typeSize;
                    statements.Add(ExpressionStatement(
                        AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                            IdentifierName("index"),
                            LiteralExpression(SyntaxKind.NumericLiteralExpression,
                                Literal((int)typeMapping?.CType.SizeInBytes)))));
                }
            }

            return statements;
        }

        private ExpressionSyntax GenerateReadPrimitiveExpression(string cSharpTypeName)
        {
            return cSharpTypeName switch
            {
                "int" => InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("BinaryPrimitives"),
                        IdentifierName("ReadInt32LittleEndian")))
                    .AddArgumentListArguments(
                        Argument(InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frameBytes"),
                                IdentifierName("Slice")))
                            .AddArgumentListArguments(
                                Argument(IdentifierName("index")),
                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(4)))))),

                "uint" => InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("BinaryPrimitives"),
                        IdentifierName("ReadUInt32LittleEndian")))
                    .AddArgumentListArguments(
                        Argument(InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frameBytes"),
                                IdentifierName("Slice")))
                            .AddArgumentListArguments(
                                Argument(IdentifierName("index")),
                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(4)))))),

                "short" => InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("BinaryPrimitives"),
                        IdentifierName("ReadInt16LittleEndian")))
                    .AddArgumentListArguments(
                        Argument(InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frameBytes"),
                                IdentifierName("Slice")))
                            .AddArgumentListArguments(
                                Argument(IdentifierName("index")),
                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(2)))))),

                "ushort" => InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("BinaryPrimitives"),
                        IdentifierName("ReadUInt16LittleEndian")))
                    .AddArgumentListArguments(
                        Argument(InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frameBytes"),
                                IdentifierName("Slice")))
                            .AddArgumentListArguments(
                                Argument(IdentifierName("index")),
                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(2)))))),

                "long" => InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("BinaryPrimitives"),
                        IdentifierName("ReadInt64LittleEndian")))
                    .AddArgumentListArguments(
                        Argument(InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frameBytes"),
                                IdentifierName("Slice")))
                            .AddArgumentListArguments(
                                Argument(IdentifierName("index")),
                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(8)))))),

                "ulong" => InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("BinaryPrimitives"),
                        IdentifierName("ReadUInt64LittleEndian")))
                    .AddArgumentListArguments(
                        Argument(InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("frameBytes"),
                                IdentifierName("Slice")))
                            .AddArgumentListArguments(
                                Argument(IdentifierName("index")),
                                Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(8)))))),

                "byte" => ElementAccessExpression(IdentifierName("frameBytes"))
                    .AddArgumentListArguments(Argument(IdentifierName("index"))),

                "sbyte" => CastExpression(ParseTypeName("sbyte"),
                    ElementAccessExpression(IdentifierName("frameBytes"))
                        .AddArgumentListArguments(Argument(IdentifierName("index")))),

                "bool" => BinaryExpression(SyntaxKind.EqualsExpression,
                    ParenthesizedExpression(
                        BinaryExpression(SyntaxKind.BitwiseAndExpression,
                            ElementAccessExpression(IdentifierName("frameBytes"))
                                .AddArgumentListArguments(Argument(IdentifierName("index"))),
                            LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(1)))),
                    LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(1))),

                _ => throw new InvalidOperationException($"Unsupported primitive type: {cSharpTypeName}")
            };
        }

    }
}

