//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// Get the secondary ZLL (touchlink) channel mask.
/// Frame value: 0x00DA
/// </summary>
public class GetZllSecondaryChannelMaskResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The secondary ZLL channel mask
    /// </summary>
    public uint Zllsecondarychannelmask { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetZllSecondaryChannelMaskResponse frame = new GetZllSecondaryChannelMaskResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Zllsecondarychannelmask = BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
		index += 4;

		return frame;
	}
}
