//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// Informs the ZLL API that application scanning is complete
/// Frame value: 0x00F6
/// </summary>
public class ZllScanningCompleteResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		ZllScanningCompleteResponse frame = new ZllScanningCompleteResponse();
	}
}
}
