//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.ZLL.Frames;

/// <summary>
/// Set the ZLL data token.
/// Frame value: 0x00BD
/// </summary>
public class ZllSetDataTokenResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		ZllSetDataTokenResponse frame = new ZllSetDataTokenResponse();
	}
}
}
