#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Binding.Frames;
/// <summary>
/// The NCP used the external binding modification policy to decide how to handle a remote set binding request. The Host cannot change the current decision, but it can change the policy for future decisions using the &lt;i&gt;setPolicy&lt;/i&gt; command.
/// Frame value: 0x0031
/// </summary>
public class RemoteSetBindingHandlerRequest : EzspFrameRequestV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x0031; }

    /// <summary>
    /// Creates the parameters for this frame
    /// </summary>
    /// <returns>The frame parameters as a byte array</returns>
    protected override byte[] CreateParameters()
    {
        return new byte[]
        {
        };
    }
}
#endif