//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Binding.Frames;

/// <summary>
/// The NCP used the external binding modification policy to decide how to handle a remote set binding request. The Host cannot change the current decision, but it can change the policy for future decisions using the &lt;i&gt;setPolicy&lt;/i&gt; command.
/// Frame value: 0x0031
/// </summary>
public class RemoteSetBindingHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The requested binding.
    /// </summary>
    public sl_zigbee_binding_table_entry_t entry { get; set; }

    /// <summary>
    /// The index at which the binding was added.
    /// </summary>
    public byte index { get; set; }

    /// <summary>
    /// SL_STATUS_OK if the binding was added to the table and any other status if not.
    /// </summary>
    public sl_status_t policyDecision { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		RemoteSetBindingHandlerResponse frame = new RemoteSetBindingHandlerResponse();
		frame.entry = 		frame.index = BitConverter.ReadByte();
		frame.policyDecision = 	}
}
}
