//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Frames;

/// <summary>
/// A callback invoked by the ZigBee GP stack when a GPDF is received.
/// Frame value: 0x00C5
/// </summary>
public class GpepIncomingMessageHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// GP parameters list represented as a macro for GP endpoint incoming message handler and callbacks prototypes.
    /// </summary>
    public sl_zigbee_gp_params_t param { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GpepIncomingMessageHandlerResponse frame = new GpepIncomingMessageHandlerResponse();
		frame.param = 	}
}
}
