//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Frames;

/// <summary>
/// Clear the entire sink table
/// Frame value: 0x00E2
/// </summary>
public class GpSinkTableClearAllResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GpSinkTableClearAllResponse frame = new GpSinkTableClearAllResponse();
	}
}
}
