//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Frames;

/// <summary>
/// Return number of active entries in sink table.
/// Frame value: 0x0118
/// </summary>
public class GpSinkTableGetNumberOfActiveEntriesResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Number of active entries in sink table.
    /// </summary>
    public byte number_of_entries { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GpSinkTableGetNumberOfActiveEntriesResponse frame = new GpSinkTableGetNumberOfActiveEntriesResponse();
		frame.number_of_entries = BitConverter.ReadByte();
	}
}
}
