//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Gets the EUI64 and short ID of an address table entry.
/// Frame value: 0x005E
/// </summary>
public class GetAddressTableInfoResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_status_t value indicating success or the reason for failure.
    /// </summary>
    public sl_status_t Status { get; set; }

    /// <summary>
    /// One of the following: The short ID corresponding to the remote node whose EUI64 is stored in the address table at the given index. SL_ZIGBEE_UNKNOWN_NODE_ID - Indicates that the EUI64 stored in the address table at the given index is valid but the short ID is currently unknown. SL_ZIGBEE_DISCOVERY_ACTIVE_NODE_ID - Indicates that the EUI64 stored in the address table at the given location is valid and network address discovery is underway. SL_ZIGBEE_TABLE_ENTRY_UNUSED_NODE_ID - Indicates that the entry stored in the address table at the given index is not in use.
    /// </summary>
    public sl_802154_short_addr_t Nodeid { get; set; }

    /// <summary>
    /// The EUI64 of the address table entry is copied to this location.
    /// </summary>
    public sl_802154_long_addr_t Eui64 { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetAddressTableInfoResponse frame = new GetAddressTableInfoResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;
		frame.Nodeid = /* TODO: Implement parsing for type sl_802154_short_addr_t */ null;
		index += 0;
		frame.Eui64 = /* TODO: Implement parsing for type sl_802154_long_addr_t */ null;
		index += 0;

		return frame;
	}
}
