//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Gets the priority masks and related variables for choosing the best beacon.
/// Frame value: 0x00F3
/// </summary>
public class GetBeaconClassificationParamsResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The attempt to get the pramaters returns SL_STATUS_OK
    /// </summary>
    public sl_status_t Status { get; set; }

    /// <summary>
    /// Gets the beacon prioritization related variable
    /// </summary>
    public sl_zigbee_beacon_classification_params_t Param { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetBeaconClassificationParamsResponse frame = new GetBeaconClassificationParamsResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;
		frame.Param = /* TODO: Implement parsing for type sl_zigbee_beacon_classification_params_t */ null;
		index += 0;

		return frame;
	}
}
