//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Indicates that the local node received a data poll from a child.
/// Frame value: 0x0044
/// </summary>
public class PollHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The node ID of the child that is requesting data.
    /// </summary>
    public sl_802154_short_addr_t Childid { get; set; }

    /// <summary>
    /// True if transmit is expected, false otherwise.
    /// </summary>
    public bool Transmitexpected { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		PollHandlerResponse frame = new PollHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Childid = /* TODO: Implement parsing for type sl_802154_short_addr_t */ null;
		index += 0;
		frame.Transmitexpected = frameBytes[index];
		index += 1;

		return frame;
	}
}
