//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Messaging.Frames;

/// <summary>
/// Reschedule sending link status message, with first one being sent immediately.
/// Frame value: 0x011B
/// </summary>
public class RescheduleLinkStatusMsgRequest : EzspFrameRequestV8Plus
{
}
