#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Types;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.TokenInterface.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.TokenInterface.Frames;
/// <summary>
/// Gets the total number of tokens.
/// Frame value: 0x0100
/// </summary>
public class GetTokenCountResponse : EzspFrameResponseV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x0100; }
    /// <summary>
    /// Total number of tokens.
    /// </summary>
    public uint Count { get; set; }

    public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
    {
        EmberResponseHeader header = EzspFrameResponseV8Plus.ParseHeader(frameBytes);
        GetTokenCountResponse frame = new GetTokenCountResponse();
        int index = Constants.EmberFrameHeaderLength;
        frame.Count = BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
        index += 4;
        return frame;
    }
}
#endif