#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.TokenInterface.Frames;

/// <summary>
/// Gets the token information for a single token at provided index
/// Frame value: 0x0101
/// </summary>
public class GetTokenInfoRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Index of the token in the token table for which information is needed.
    /// </summary>
    public byte index { get; set; }

}

#endif