//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Configures endpoint information on the NCP. The NCP does not remember these settings after a reset. Endpoints can be added by the Host after the NCP has reset. Once the status of the stack changes to SL_STATUS_NETWORK_UP, endpoints can no longer be added and this command will respond with SL_ZIGBEE_EZSP_ERROR_INVALID_CALL.
/// Frame value: 0x0002
/// </summary>
public class AddEndpointRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// The application endpoint to be added.
    /// </summary>
    public byte endpoint { get; set; }

    /// <summary>
    /// The endpoint&apos;s application profile.
    /// </summary>
    public ushort profileId { get; set; }

    /// <summary>
    /// The endpoint&apos;s device ID within the application profile.
    /// </summary>
    public ushort deviceId { get; set; }

    /// <summary>
    /// The endpoint&apos;s device version.
    /// </summary>
    public byte deviceVersion { get; set; }

    /// <summary>
    /// The number of cluster IDs in &lt;i&gt;inputClusterList&lt;/i&gt;.
    /// </summary>
    public byte inputClusterCount { get; set; }

    /// <summary>
    /// The number of cluster IDs in &lt;i&gt;outputClusterList&lt;/i&gt;.
    /// </summary>
    public byte outputClusterCount { get; set; }

    /// <summary>
    /// Input cluster IDs the endpoint will accept.
    /// </summary>
    public uint16_t[inputClusterCount] inputClusterList { get; set; }

    /// <summary>
    /// Output cluster IDs the endpoint may send.
    /// </summary>
    public uint16_t[outputClusterCount] outputClusterList { get; set; }

}
