//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Retrieve one of the cluster IDs associated with the given endpoint.
/// Frame value: 0x0131
/// </summary>
public class GetEndpointClusterResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// ID of the requested cluster.
    /// </summary>
    public ushort endpoint_cluster { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GetEndpointClusterResponse frame = new GetEndpointClusterResponse();
		frame.endpoint_cluster = BitConverter.ReadUShort();
	}
}
}
