//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Read attribute data on NCP endpoints.
/// Frame value: 0x0108
/// </summary>
public class ReadAttributeRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Endpoint
    /// </summary>
    public byte endpoint { get; set; }

    /// <summary>
    /// Cluster.
    /// </summary>
    public ushort cluster { get; set; }

    /// <summary>
    /// Attribute ID.
    /// </summary>
    public ushort attributeId { get; set; }

    /// <summary>
    /// Mask.
    /// </summary>
    public byte mask { get; set; }

    /// <summary>
    /// Manufacturer code.
    /// </summary>
    public ushort manufacturerCode { get; set; }

}
