//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Allows the Host to control the broadcast behaviour of a routing device used by the NCP.
/// Frame value: 0x0105
/// </summary>
public class SetPassiveAckConfigRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Passive ack config enum.
    /// </summary>
    public byte config { get; set; }

    /// <summary>
    /// The minimum number of acknowledgments (re-broadcasts) to wait for until deeming the broadcast transmission complete.
    /// </summary>
    public byte minAcksNeeded { get; set; }

}
