#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Mfglib.Frames;

/// <summary>
/// First select the transmit power mode, and then include a method for selecting the radio transmit power. The valid power settings depend upon the specific radio in use. Ember radios have discrete power settings, and then requested power is rounded to a valid power setting; the actual power output is available to the caller via mfglibInternalGetPower().
/// Frame value: 0x008c
/// </summary>
public class MfglibInternalSetPowerRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x008c; } }

    /// <summary>
    /// Power mode. Refer to txPowerModes in stack/include/sl_zigbee_types.h for possible values.
    /// </summary>
	public ushort TxPowerMode { get; set; }

    /// <summary>
    /// Power in units of dBm. Refer to radio data sheet for valid range.
    /// </summary>
	public sbyte Power { get; set; }

}

#endif