#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Retrieve the endpoint number located at the specified index.
/// Frame value: 0x012E
/// </summary>
public class GetEndpointResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Endpoint number at the index.
    /// </summary>
	public byte Endpoint { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetEndpointResponse frame = new GetEndpointResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Endpoint = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif