#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Triggers a pan id update message.
/// Frame value: 0x0057
/// </summary>
public class SendPanIdUpdateResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// true if the request was successfully handed to the stack, false otherwise
    /// </summary>
    public bool Status { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		SendPanIdUpdateResponse frame = new SendPanIdUpdateResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = ((frameBytes[index] & 1) == 1);
		index += 1;

		return frame;
	}
}

#endif