#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Configuration.Frames;

/// <summary>
/// Allows the Host to change the policies used by the NCP to make fast decisions.
/// Frame value: 0x0055
/// </summary>
public class SetPolicyRequest : EzspFrameRequestV8Plus
{
    /// <summary>
    /// Identifies which policy to modify.
    /// </summary>
	public ZigbeeEzspPolicyId policyId { get; set; }

    /// <summary>
    /// The new decision for the specified policy.
    /// </summary>
	public ZigbeeEzspDecisionId decisionId { get; set; }

}

#endif