#if VERSION_2025_6_2
namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;

/// <summary>
/// The status of the attempt to establish a key.
/// </summary>
public enum ZigbeeKeyStatus : byte
{
		SL_ZIGBEE_APP_LINK_KEY_ESTABLISHED = 0x01,
		SL_ZIGBEE_TRUST_CENTER_LINK_KEY_ESTABLISHED = 0x03,
		SL_ZIGBEE_KEY_ESTABLISHMENT_TIMEOUT = 0x04,
		SL_ZIGBEE_KEY_TABLE_FULL = 0x05,
		SL_ZIGBEE_TC_RESPONDED_TO_KEY_REQUEST = 0x06,
		SL_ZIGBEE_TC_APP_KEY_SENT_TO_REQUESTER = 0x07,
		SL_ZIGBEE_TC_RESPONSE_TO_KEY_REQUEST_FAILED = 0x08,
		SL_ZIGBEE_TC_REQUEST_KEY_TYPE_NOT_SUPPORTED = 0x09,
		SL_ZIGBEE_TC_NO_LINK_KEY_FOR_REQUESTER = 0x0A,
		SL_ZIGBEE_TC_REQUESTER_EUI64_UNKNOWN = 0x0B,
		SL_ZIGBEE_TC_RECEIVED_FIRST_APP_KEY_REQUEST = 0x0C,
		SL_ZIGBEE_TC_TIMEOUT_WAITING_FOR_SECOND_APP_KEY_REQUEST = 0x0D,
		SL_ZIGBEE_TC_NON_MATCHING_APP_KEY_REQUEST_RECEIVED = 0x0E,
		SL_ZIGBEE_TC_FAILED_TO_SEND_APP_KEYS = 0x0F,
		SL_ZIGBEE_TC_FAILED_TO_STORE_APP_KEY_REQUEST = 0x10,
		SL_ZIGBEE_TC_REJECTED_APP_KEY_REQUEST = 0x11
}

#endif