<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<LangVersion>default</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Version>1.5.0</Version>
		<Authors>ZigBeeNet Contributors</Authors>
		<Company>ZigBeeNet</Company>
		<PackageLicenseExpression>EPL-1.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/zigbeenet/ZigbeeNet</PackageProjectUrl>
		<PackageIconUrl>https://github.com/zigbeenet/ZigbeeNet/blob/master/icon.png?raw=true</PackageIconUrl>
		<RepositoryUrl>https://github.com/zigbeenet/ZigbeeNet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>zigbee;netstandard;smart home;philips hue;ikea tradfri;innr;Ember;Silicon Labs</PackageTags>
		<Description>This package can be used in combination with the ZigBeeNet package and is the dongle implementation for a Silicon Labs Ember chip</Description>
		<Nullable>enable</Nullable>
	</PropertyGroup>


	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
		<DefineConstants>$(DefineConstants);VERSION_2025_6_2</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
		<DefineConstants>$(DefineConstants);VERSION_2025_6_2</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
		<DefineConstants>$(DefineConstants);VERSION_2025_6_2</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Internal\Serializer\EzspDeserializer.cs"/>
		<Compile Remove="Internal\Serializer\EzspSerializer.cs"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SiliconLabs.ASH\SiliconLabs.ASH.csproj"/>
		<ProjectReference Include="..\ZigBeeNet\ZigBeeNet.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Ezsp\Autogenerated\"/>
		<Folder Include="Ezsp\Frames\"/>
		<Folder Include="Ezsp\Structures\"/>
	</ItemGroup>

	<ItemGroup>
		<None Include="Internal\Serializer\EzspDeserializer.cs"/>
		<None Include="Internal\Serializer\EzspSerializer.cs"/>
		<Compile Remove="Internal\Ash\AshErrorCode.cs"/>
		<None Include="Internal\Ash\AshErrorCode.cs"/>
		<Compile Remove="Internal\Ash\AshFrame.cs"/>
		<None Include="Internal\Ash\AshFrame.cs"/>
		<Compile Remove="Internal\Ash\AshFrameAck.cs"/>
		<None Include="Internal\Ash\AshFrameAck.cs"/>
		<Compile Remove="Internal\Ash\AshFrameData.cs"/>
		<None Include="Internal\Ash\AshFrameData.cs"/>
		<Compile Remove="Internal\Ash\AshFrameError.cs"/>
		<None Include="Internal\Ash\AshFrameError.cs"/>
		<Compile Remove="Internal\Ash\AshFrameHandler.cs"/>
		<None Include="Internal\Ash\AshFrameHandler.cs"/>
		<Compile Remove="Internal\Ash\AshFrameNak.cs"/>
		<None Include="Internal\Ash\AshFrameNak.cs"/>
		<Compile Remove="Internal\Ash\AshFrameRst.cs"/>
		<None Include="Internal\Ash\AshFrameRst.cs"/>
		<Compile Remove="Internal\Ash\AshFrameRstAck.cs"/>
		<None Include="Internal\Ash\AshFrameRstAck.cs"/>
		<Compile Remove="Internal\Transaction\ITransaction.cs"/>
		<None Include="Internal\Transaction\ITransaction.cs"/>
		<Compile Remove="Internal\Transaction\MultiResponseTransaction.cs"/>
		<None Include="Internal\Transaction\MultiResponseTransaction.cs"/>
		<Compile Remove="Internal\Transaction\SingleResponseTransaction.cs"/>
		<None Include="Internal\Transaction\SingleResponseTransaction.cs"/>
	</ItemGroup>

	<ItemGroup>
	  <EditorConfigFiles Remove=".editorconfig" />
	</ItemGroup>
</Project>