using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models.TypeMapper;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Parser;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Utility;
using static System.Collections.Specialized.BitVector32;

namespace ZigBeeNet.EmberV8Plus.CodeGenerator.Services
{
    internal class ComplexTypeDefinitionProcessorService
    {
        private readonly ILogger<SimpleTypeDefinitionProcessorService> _logger;
        private readonly TypeMapperService _typeMapperService;
        private readonly FileService _fileService;

        public ComplexTypeDefinitionProcessorService(ILoggerFactory __loggerFactory, TypeMapperService typeMapperService, FileService fileService)
        {
            _logger = __loggerFactory.CreateLogger<SimpleTypeDefinitionProcessorService>();
            _typeMapperService = typeMapperService;
            _fileService = fileService;
        }
        
        internal bool ProcessComplexTypeDefinition(string sectionName, Typedef typedef)
        {
            ComplexTypedefDefinition complex = (ComplexTypedefDefinition)typedef.Definition;
            string sanitizedSectionName = Sanitize.SectionName(sectionName);

            _logger.LogInformation("\t\t- {name} (complex): {fieldCount} fields", typedef.Name, complex.Fields.Count);

            StringBuilder sb = new StringBuilder();

            TextHelper.AppendAutoGeneratedHeader(sb);
            sb.AppendLine();

            // Add XML documentation
            if (!string.IsNullOrEmpty(typedef.Description))
            {
                TextHelper.AppendBasicSummary(sb, typedef.Description);
            }

            sb.AppendLine();
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;");
            if (sectionName != "Common")
            {
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;");
            }
            sb.AppendLine();

            // Generate namespace
            sb.AppendLine($"namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Types;");
            sb.AppendLine();

            // Generate struct definition
            string structureName = Sanitize.StructureName(typedef.Name);

            // If structureName starts with a digit, prefix with '_' to create a valid identifier
            if (!string.IsNullOrEmpty(structureName) && char.IsDigit(structureName[0]))
            {
                structureName = "_" + structureName;
            }
            
            sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"public struct {structureName}");
            sb.AppendLine("{");

            // Add fields
            foreach (var field in complex.Fields)
            {
                if (!string.IsNullOrEmpty(field.Description))
                {
                    TextHelper.AppendBasicSummary(sb, field.Description, 1);
                }

                // Check if the field name contains array notation (e.g., fieldName[SIZE])
                int nameBracketIndex = field.Name?.IndexOf('[') ?? -1;
                if (nameBracketIndex >= 0)
                {
                    // Extract field name and array size from name
                    string fieldName = field.Name![..nameBracketIndex];
                    string arrayPart = field.Name[nameBracketIndex..];
                    string arraySize = arrayPart.Trim('[', ']');
                    
                    TypeMapping? csharpBaseType = _typeMapperService.GetTypeMapping(field.Type);
                    
                    string santizedTypeName = Sanitize.TypeName(csharpBaseType?.CSharpType.Name);

                    // Check if array size is numeric (compile-time constant)
                    if (int.TryParse(arraySize, out _))
                    {
                        sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {arraySize})]");
                        sb.AppendLine($"\tpublic {santizedTypeName}[] {fieldName};");
                    }
                    else
                    {
                        // Array size is a symbolic constant - use a comment and skip
                        sb.AppendLine($"\t// Array field with symbolic size: {arraySize}");
                        sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {MapCConstants.MapConstant(arraySize)})]");
                        sb.AppendLine($"\tpublic {santizedTypeName}[] {fieldName};");
                    }
                }
                // Check if the type contains array notation (e.g., uint8_t[8])
                else if (field.Type?.IndexOf('[') >= 0)
                {
                    int typeBracketIndex = field.Type.IndexOf('[');
                    // Extract base type and array size
                    string baseType = field.Type[..typeBracketIndex];
                    string arrayPart = field.Type[typeBracketIndex..];
                    TypeMapping? csharpBaseType = _typeMapperService.GetTypeMapping(baseType);
                    string santizedTypeName = Sanitize.TypeName(csharpBaseType?.CSharpType.Name);


                    // Extract array size from [N] format
                    string arraySize = arrayPart.Trim('[', ']');

                    // Check if array size is numeric (compile-time constant)
                    if (int.TryParse(arraySize, out _))
                    {
                        sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {arraySize})]");
                        sb.AppendLine($"\tpublic {santizedTypeName}[] {field.Name};");
                    }
                    else
                    {
                        // Array size is a symbolic constant - use a comment and skip
                        sb.AppendLine($"\t// Array field with symbolic size: {arraySize}");
                        sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {arraySize})]");
                        sb.AppendLine($"\tpublic {santizedTypeName}[] {field.Name};");
                    }
                }
                else
                {
                    // Simple scalar type
                    TypeMapping? baseType = _typeMapperService.GetTypeMapping(field.Type);
                    string santizedTypeName = Sanitize.TypeName(baseType?.CSharpType.Name);
                    
                    if (baseType?.CType.IsArray == false)
                    {
                        // Special case: if the field type is "MacTransmitCallback", 
                        if (field.Type == "MacTransmitCallback")
                        {
                            sb.AppendLine($"\t// Note: MacTransmitCallback is defined as a function pointer, used only locally, not serialized.");
                            sb.AppendLine($"[NonSerialized]");
                        }
                        sb.AppendLine($"\tpublic {santizedTypeName} {field.Name};");
                    }
                    else
                    {
                        sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {baseType?.CType.ArrayLength})]");
                        sb.AppendLine($"\tpublic {santizedTypeName}[] {field.Name};");
                    }
                    sb.AppendLine();
                }

            }

            sb.AppendLine("}");
            sb.AppendLine();

            // Finished generating struct definition

            // Process type mapping

            bool isVariableLengthStruct = complex.Fields.Any(field => field.Type.Contains('[') == true && field.Type.GetArrayDefinitionSize() == -1);
            int typeSizeInBytes = -1;

            if (isVariableLengthStruct == false)
            {
                typeSizeInBytes = (typedef.Definition as ComplexTypedefDefinition)!.Fields.Sum(field =>
                {
                    TypeMapping? fieldTypeMapping = _typeMapperService.GetTypeMapping(field.Type.GetArrayDefinitionBaseType());
                    if (fieldTypeMapping is null)
                    {
                        if (field.Type == "MacTransmitCallback")
                        {
                            // Special case: MacTransmitCallback is defined as a function pointer, used only locally, not serialized.
                            return 0;
                        }
                        _logger.LogError("No type mapping found for field type {type} of field {field} in complex type {complexType} in section {section}, cannot finish",
                            field.Type, field.Name, typedef.Name, sectionName);
                        return 0;
                    }
                    else if (fieldTypeMapping.HasValue && field.Type.EndsWith(']') == true)
                    {
                        return fieldTypeMapping.Value.CType.SizeInBytes * field.Type.GetArrayDefinitionSize();
                    }
                    else
                    {
                        return fieldTypeMapping?.CType.SizeInBytes ?? 0;
                    }
                });
            }
            _typeMapperService.AddTypeMapping(
                new CType(typedef.Name, 0, typedef.Description)
                {
                    IsStruct = true,
                    SizeInBytes = typeSizeInBytes,
                    IsVariableLengthStruct = isVariableLengthStruct,
                },
                new CSharpType(Sanitize.TypeName(typedef.Name))
                {
                    IsStruct = true,
                    Namespace = $"ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Types",
                }
            );

            _fileService.SaveComplexTypeFile(sectionName, structureName, sb.ToString());

            return true;
        }
    }
}
