using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models.TypeMapper;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Parser;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Utility;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZigBeeNet.EmberV8Plus.CodeGenerator.Services
{
    internal class CSharpLanguageService
    {
        private readonly ILogger<CSharpLanguageService> _logger;
        private readonly TypeMapperService _typeMapper;

        public CSharpLanguageService(ILoggerFactory _loggerFactory, TypeMapperService typeMapper)
        {
            _logger = _loggerFactory.CreateLogger<CSharpLanguageService>();
            _typeMapper = typeMapper;
        }

        internal string GenerateVariableDeclaration(FrameArgument frameArgument, bool addSemicolon = false)
        {
            string fieldName = frameArgument.Name.AsFieldName();
            if (frameArgument.Type.IndexOf('[') > -1 && frameArgument.Type.IndexOf(']') > -1 && frameArgument.Type.IndexOf('[') < frameArgument.Type.IndexOf(']'))
            {
                string baseType = frameArgument.Type.Substring(0, frameArgument.Type.IndexOf('['));
                TypeMapping? argType = _typeMapper.GetTypeMapping(baseType);
                
                return $"{argType?.CSharpType.Name}[] {fieldName}{(addSemicolon ? ";" : String.Empty)}";
            }
            else
            {
                TypeMapping? argType = _typeMapper.GetTypeMapping(frameArgument.Type);
                return $"{argType?.CSharpType.Name} {fieldName}{(addSemicolon ? ";" : String.Empty)}";
            }
        }

        internal string GenerateVariableType(FrameArgument frameArgument)
        {
            if (frameArgument.Type.IndexOf('[') > -1 && frameArgument.Type.IndexOf(']') > -1 && frameArgument.Type.IndexOf('[') < frameArgument.Type.IndexOf(']'))
            {
                string baseType = frameArgument.Type.Substring(0, frameArgument.Type.IndexOf('['));
                TypeMapping? argType = _typeMapper.GetTypeMapping(baseType);

                return $"{argType?.CSharpType.Name}[]";
            }
            else
            {
                TypeMapping? argType = _typeMapper.GetTypeMapping(frameArgument.Type);
                return $"{argType?.CSharpType.Name}";
            }
        }

        internal void GenerateAutoGeneratedHeader(StringBuilder sb)
        {
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
        }

        //internal string GenerateFunctionHeader(StringBuilder sb, string description, int indentation = 0)
        //{
        //    if (!string.IsNullOrWhiteSpace(description))
        //    {
        //        string indent = new string('\t', indentation);

        //        sb.AppendLine($"{indent}/// <summary>");
        //        sb.AppendLine($"{indent}/// {Regex.Replace(description.XmlEscape(), @"\r\n|[\r\n]", $"\r\n{indent}/// ")}");
        //        sb.AppendLine($"{indent}/// </summary>");
        //    }
        //}

        //internal string GenerateFunctionSignature(FrameDefinition frameDefinition)
        //{
        //    StringBuilder stringBuilder = new StringBuilder();

        //    string sanitizedCommandName = Sanitize.FunctionName(frameDefinition.CommandName);

        //    string returnParameters = $"{sanitizedCommandName}Response";
        //    if (frameDefinition.ResponseArguments.Count() > 1)
        //    {
        //        returnParameters = $"({String.Join(", ", frameDefinition.ResponseArguments.Select(responseArgument => _textService.GenerateVariableDeclaration(responseArgument)))})";
        //    }
        //    else if (frameDefinition.ResponseArguments.Count() == 1)
        //    {
        //        returnParameters = _textService.GenerateVariableType(frameDefinition.ResponseArguments[0]);
        //    }
        //    else
        //    {
        //        returnParameters = $"{sanitizedCommandName}Response";
        //    }

        //    emberNCPAutoGeneratedContent.AppendLine($"\t\t");

        //    TextHelper.AppendBasicSummary(emberNCPAutoGeneratedContent, frameDefinition.Description, 1);

        //    emberNCPAutoGeneratedContent.Append($"\tpublic {returnParameters} {sanitizedCommandName}(");

        //    string inputParameters = String.Join(", ", frameDefinition.CommandArguments.Select(commandArgument => _textService.GenerateVariableDeclaration(commandArgument)));

        //    emberNCPAutoGeneratedContent.Append(inputParameters);

        //    emberNCPAutoGeneratedContent.AppendLine(")");
        //}

        internal void DocumentFunction(string functionCode, string description)
        {
            var tree = CSharpSyntaxTree.ParseText(functionCode);

            if (tree.GetRoot() is not MethodDeclarationSyntax)
            {
                   throw new ArgumentException("Provided code is not a valid method declaration.");
            }

            MethodDeclarationSyntax method = tree.GetRoot() as MethodDeclarationSyntax;
            //var root = tree.GetRoot();

            //var method = root.DescendantNodes()
            //                 .OfType<MethodDeclarationSyntax>()
            //                 .First();

            // Build XML doc comment
            var summary = SyntaxFactory.XmlSummaryElement(SyntaxFactory.XmlText(description));

            var paramElements = method.ParameterList.Parameters.Select(p =>
                SyntaxFactory.XmlParamElement(
                    p.Identifier.Text,
                    SyntaxFactory.XmlText("Parameter of type " + p.Type)));

            var returnElement = SyntaxFactory.XmlReturnsElement(
                SyntaxFactory.XmlText("Returns " + method.ReturnType.ToString()));

            var docComment = SyntaxFactory.DocumentationCommentTrivia(
                SyntaxKind.SingleLineDocumentationCommentTrivia,
                SyntaxFactory.List<XmlNodeSyntax>(
                    new XmlNodeSyntax[] { summary }
                    .Concat(paramElements)
                    .Concat(new[] { returnElement })
                ));

            // Attach to method
            var methodWithDocs = method.WithLeadingTrivia(
                SyntaxFactory.Trivia(docComment));

            Console.WriteLine(methodWithDocs.NormalizeWhitespace().ToFullString());
        }
    }
    
    }
}