using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models.TypeMapper;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Services;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Utility;

namespace ZigBeeNet.EmberV8Plus.CodeGenerator.Parser
{
    internal class FrameDefinitionProcessorService
    {
        private readonly ILogger<FrameDefinitionProcessorService> _logger;
        private readonly TypeMapperService _typeMapper;

        public FrameDefinitionProcessorService(ILoggerFactory __loggerFactory, TypeMapperService typeMapperService)
        {
            _logger = __loggerFactory.CreateLogger<FrameDefinitionProcessorService>();
            _typeMapper = typeMapperService;
        }

        /// <summary>
        /// Processes a frame definition and generates C# request class code.
        /// </summary>
        /// <param name="_logger">Logger instance for diagnostic output.</param>
        /// <param name="section">The section name (used for namespace generation).</param>
        /// <param name="frameDefinition">The frame definition to process.</param>
        /// <returns>Generated C# request class code as a string.</returns>
        internal string ProcessFrameDefinitionForRequest(string section, FrameDefinition frameDefinition)
        {
            try
            {
                if (frameDefinition == null)
                {
                    _logger.LogWarning("Frame definition is null");
                    return string.Empty;
                }

                if (string.IsNullOrWhiteSpace(frameDefinition.CommandName))
                {
                    _logger.LogWarning("Frame command name is empty");
                    return string.Empty;
                }

                var sb = new StringBuilder();

                sb.AppendLine("//------------------------------------------------------------------------------");
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine("//     This code was generated by a tool.");
                sb.AppendLine("//");
                sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
                sb.AppendLine("//     the code is regenerated.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("//------------------------------------------------------------------------------");

                sb.AppendLine("using System;");
                sb.AppendLine("using System.Buffers.Binary;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine();

                // Generate namespace
                string sanitizedSectionName = Sanitize.SectionName(section);
                sb.AppendLine($"namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Frames;");
                sb.AppendLine();

                // Generate XML documentation with frame value
                if (!string.IsNullOrWhiteSpace(frameDefinition.Description))
                {
                    sb.AppendLine("/// <summary>");
                    sb.AppendLine($"/// {frameDefinition.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                    if (!string.IsNullOrWhiteSpace(frameDefinition.Value))
                    {
                        sb.AppendLine($"/// Frame value: {frameDefinition.Value}");
                    }
                    sb.AppendLine("/// </summary>");
                }

                // Generate class declaration inheriting from EzspFrameRequest
                string className = char.ToUpper(frameDefinition.CommandName[0]) + frameDefinition.CommandName[1..] + "Request";
                sb.AppendLine($"public class {className} : EzspFrameRequestV8Plus");
                sb.AppendLine("{");

                // Generate properties for command arguments
                if (frameDefinition.CommandArguments != null && frameDefinition.CommandArguments.Count > 0)
                {
                    foreach (var arg in frameDefinition.CommandArguments)
                    {
                        if (!string.IsNullOrWhiteSpace(arg.Description))
                        {
                            sb.AppendLine("    /// <summary>");
                            sb.AppendLine($"    /// {arg.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                            sb.AppendLine("    /// </summary>");
                        }

                        // Check if the field name contains array notation (e.g., fieldName[SIZE])
                        int typeBracketIndex = arg.Type?.IndexOf('[') ?? -1;
                        if (typeBracketIndex >= 0)
                        {
                            // Extract field name and array size from name
                            string fieldArrayType = arg.Type![..typeBracketIndex];
                            string arrayPart = arg.Type[typeBracketIndex..];
                            string arraySize = arrayPart.Trim('[', ']');
                            cMapping csharpBaseType = MapCTypes.MapBaseCType(fieldArrayType);
                            string santizedTypeName = Sanitize.TypeName(csharpBaseType.cSharpTypeName);

                            // Check if array size is numeric (compile-time constant)
                            if (int.TryParse(arraySize, out _))
                            {
                                //sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {arraySize})]");
                                sb.AppendLine($"\tpublic {santizedTypeName}[] {arg.Name};");
                            }
                            else
                            {
                                // Array size is a symbolic constant 
                                sb.AppendLine($"\t// Array field with symbolic size: {arraySize}");
                                //sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {MapCConstants.MapConstant(arraySize)})]");
                                sb.AppendLine($"\tpublic {santizedTypeName}[] {arg.Name};");
                            }
                        }
                        else
                        {
                            cMapping csharpType = MapCTypes.MapBaseCType(arg.Type);
                            string sanitizedTypeName = Sanitize.TypeName(csharpType.cSharpTypeName);
                            if (char.IsDigit(sanitizedTypeName[0]) == true)
                            {
                                sanitizedTypeName = "_" + sanitizedTypeName;
                            }
                            sb.AppendLine($"    public {sanitizedTypeName} {arg.Name} {{ get; set; }}");
                            sb.AppendLine();
                        }
                    }
                }

                sb.AppendLine("}");

                _logger.LogDebug("Generated request class {commandName} with {argCount} arguments",
                    className, frameDefinition.CommandArguments?.Count ?? 0);

                return sb.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing frame definition for request {commandName}",
                    frameDefinition?.CommandName ?? "unknown");
                return string.Empty;
            }
        }

        /// <summary>
        /// Processes a frame definition and generates C# response class code.
        /// </summary>
        /// <param name="_logger">Logger instance for diagnostic output.</param>
        /// <param name="section">The section name (used for namespace generation).</param>
        /// <param name="frameDefinition">The frame definition to process.</param>
        /// <returns>Generated C# response class code as a string.</returns>
        internal string ProcessFrameDefinitionForResponse(string section, FrameDefinition frameDefinition)
        {
            try
            {
                if (frameDefinition == null)
                {
                    _logger.LogWarning("Frame definition is null");
                    return string.Empty;
                }

                if (string.IsNullOrWhiteSpace(frameDefinition.CommandName))
                {
                    _logger.LogWarning("Frame command name is empty");
                    return string.Empty;
                }

                var sb = new StringBuilder();

                sb.AppendLine("//------------------------------------------------------------------------------");
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine("//     This code was generated by a tool.");
                sb.AppendLine("//");
                sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
                sb.AppendLine("//     the code is regenerated.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("//------------------------------------------------------------------------------");

                sb.AppendLine("using System;");
                sb.AppendLine("using System.Buffers.Binary;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine();

                // Generate namespace
                string sanitizedSectionName = Sanitize.SectionName(section);
                sb.AppendLine($"namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Frames;");
                sb.AppendLine();

                // Generate XML documentation with frame value
                if (!string.IsNullOrWhiteSpace(frameDefinition.Description))
                {
                    sb.AppendLine("/// <summary>");
                    sb.AppendLine($"/// {frameDefinition.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                    if (!string.IsNullOrWhiteSpace(frameDefinition.Value))
                    {
                        sb.AppendLine($"/// Frame value: {frameDefinition.Value}");
                    }
                    sb.AppendLine("/// </summary>");
                }

                string className = char.ToUpper(frameDefinition.CommandName[0]) + frameDefinition.CommandName[1..] + "Response";
                // Generate class declaration inheriting from EzspFrameResponse
                sb.AppendLine($"public class {className} : EzspFrameResponseV8Plus");
                sb.AppendLine("{");

                // Generate properties for response arguments
                if (frameDefinition.ResponseArguments != null && frameDefinition.ResponseArguments.Count > 0)
                {
                    foreach (var arg in frameDefinition.ResponseArguments)
                    {
                        if (!string.IsNullOrWhiteSpace(arg.Description))
                        {
                            sb.AppendLine("    /// <summary>");
                            sb.AppendLine($"    /// {arg.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                            sb.AppendLine("    /// </summary>");
                        }

                        // Check if the field name contains array notation (e.g., fieldName[SIZE])
                        int typeBracketIndex = arg.Type?.IndexOf('[') ?? -1;
                        if (typeBracketIndex >= 0)
                        {
                            // Extract field name and array size from name
                            string fieldArrayType = arg.Type![..typeBracketIndex];
                            string arrayPart = arg.Type[typeBracketIndex..];
                            string arraySize = arrayPart.Trim('[', ']');
                            cMapping csharpBaseType = MapCTypes.MapBaseCType(fieldArrayType);
                            string santizedTypeName = Sanitize.TypeName(csharpBaseType.cSharpTypeName);

                            // Check if array size is numeric (compile-time constant)
                            if (int.TryParse(arraySize, out _))
                            {
                                sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {arraySize})]");
                                sb.AppendLine($"\tpublic {santizedTypeName}[] {arg.Name};");
                            }
                            else
                            {
                                // Array size is a symbolic constant 
                                sb.AppendLine($"\t// Array field with symbolic size: {arraySize}");
                                //sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {MapCConstants.MapConstant(arraySize)})]");
                                sb.AppendLine($"\tpublic {santizedTypeName}[] {arg.Name};");
                            }
                        }
                        else
                        {
                            cMapping csharpType = MapCTypes.MapBaseCType(arg.Type);
                            string sanitizedTypeName = Sanitize.TypeName(csharpType.cSharpTypeName);
                            if (char.IsDigit(sanitizedTypeName[0]) == true)
                            {
                                sanitizedTypeName = "_" + sanitizedTypeName;
                            }
                            sb.AppendLine($"    public {sanitizedTypeName} {Sanitize.PropertyName(arg.Name)} {{ get; set; }}");
                            sb.AppendLine();
                        }
                    }
                }

                sb.AppendLine($"\tpublic static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)");
                sb.AppendLine("\t{");
                sb.AppendLine($"\t\t{className} frame = new {className}();");
                sb.AppendLine($"\t\tint index = frame.ParseHeader(frameBytes);");
                sb.AppendLine();
                if (frameDefinition.ResponseArguments != null && frameDefinition.ResponseArguments.Count > 0)
                {
                    int frameBytesPosition = 0;
                    foreach (var arg in frameDefinition.ResponseArguments)
                    {
                        //if (!string.IsNullOrWhiteSpace(arg.Description))
                        //{
                        //    sb.AppendLine("    /// <summary>");
                        //    sb.AppendLine($"    /// {arg.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                        //    sb.AppendLine("    /// </summary>");
                        //}

                        TypeMapping? typeMapping = _typeMapper.GetTypeMapping(arg.Type);

                        if (typeMapping != null)
                        {
                            sb.Append($"\t\tframe.{Sanitize.PropertyName(arg.Name)} = ");

                            if (typeMapping?.CType.IsEnum == true)
                            {
                                TypeMapping baseTypeMapping = _typeMapper.GetTypeMapping(typeMapping?.CType.UnderlyingTypeName ?? "") ?? throw new InvalidOperationException($"No type mapping found for underlying type {typeMapping?.CType.UnderlyingTypeName} of enum {typeMapping?.CType.Name}");
                                sb.Append($"({typeMapping?.CSharpType.Name})");
                                sb.AppendLine(ReadPrimitiveTypeString(baseTypeMapping.CType.Name));
                            }
                            else
                            {
                                sb.AppendLine(ReadPrimitiveTypeString(typeMapping.Value.CType.Name));
                            }


                            sb.AppendLine($"\t\tindex += {typeMapping?.CType.SizeInBytes};");

                            frameBytesPosition += typeMapping?.CType.SizeInBytes ?? 0;
                        }
                        else
                        {
                            _logger.LogError("No type mapping found for argument {argName} of type {argType} in frame {commandName}", arg.Name, arg.Type, frameDefinition.CommandName);
                            sb.AppendLine($"\t\t// Unknown type mapping for argument {arg.Name} of type {arg.Type}");
                            return string.Empty;
                        }
                    }
                }


                sb.AppendLine();
                sb.AppendLine($"\t\treturn frame;");
                sb.AppendLine("\t}");

                sb.AppendLine("}");

                _logger.LogDebug("Generated response class {commandName} with {argCount} arguments",
                    className, frameDefinition.ResponseArguments?.Count ?? 0);

                return sb.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing frame definition for response {commandName}",
                    frameDefinition?.CommandName ?? "unknown");
                return string.Empty;
            }
        }

        private string ReadPrimitiveTypeString(string cPrimitveName)
        {
            return cPrimitveName switch
            {
                "int32_t" => "BinaryPrimitives.ReadInt32LittleEndian(frameBytes.Slice(index, 4));",
                "uint32_t" => "BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, {4));",
                "int16_t" => "BinaryPrimitives.ReadInt16LittleEndian(frameBytes.Slice(index, 2));",
                "uint16_t" => "BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));",
                "int64_t" => "BinaryPrimitives.ReadInt64LittleEndian(frameBytes.Slice(index, 8));",
                "uint64_t" => "BinaryPrimitives.ReadUInt64LittleEndian(frameBytes.Slice(index, 8));",
                "uint8_t" => "frameBytes[index];",
                "int8_t" => "frameBytes[index];",
                "bool" => "((frameBytes[index] & 1) == 1);",
                _ => throw new Exception($"Not a primitive type: {cPrimitveName}"),
            };
        }


    }
}
