using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Models.TypeMapper;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Services;
using ZigBeeNet.EmberV8Plus.CodeGenerator.Utility;

namespace ZigBeeNet.EmberV8Plus.CodeGenerator.Parser
{
    internal class FrameDefinitionProcessorService
    {
        private readonly ILogger<FrameDefinitionProcessorService> _logger;
        private readonly TypeMapperService _typeMapper;
        private readonly CSharpLanguageService _cSharpLanguageService;
        private readonly FileService _fileService;

        public FrameDefinitionProcessorService(ILoggerFactory _loggerFactory, TypeMapperService typeMapperService, CSharpLanguageService cSharpLanguageService, FileService fileService)
        {
            _logger = _loggerFactory.CreateLogger<FrameDefinitionProcessorService>();
            _typeMapper = typeMapperService;
            _cSharpLanguageService = cSharpLanguageService;
            _fileService = fileService;
        }

        /// <summary>
        /// Processes a frame definition and generates C# request class code.
        /// </summary>
        /// <param name="_logger">Logger instance for diagnostic output.</param>
        /// <param name="sectionName">The section name (used for namespace generation).</param>
        /// <param name="frameDefinition">The frame definition to process.</param>
        /// <returns>Generated C# request class code as a string.</returns>
        internal void ProcessFrameDefinitionForRequest(string sectionName, FrameDefinition frameDefinition)
        {
            string sanitizedSectionName = Sanitize.SectionName(sectionName);

            try
            {
                if (frameDefinition == null)
                {
                    _logger.LogWarning("Frame definition is null");
                }

                if (string.IsNullOrWhiteSpace(frameDefinition.CommandName))
                {
                    _logger.LogWarning("Frame command name is empty");
                }

                var sb = new StringBuilder();

                _cSharpLanguageService.GenerateAutoGeneratedHeader(sb);

                sb.AppendLine("using System;");
                sb.AppendLine("using System.Buffers.Binary;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;");
                if (_typeMapper.SectionTypeMappingExists(sanitizedSectionName) == true)
                {
                    sb.AppendLine($"using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Types;");
                }
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine();

                // Generate namespace
                sb.AppendLine($"namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Frames;");
                sb.AppendLine();

                // Generate XML documentation with frame value
                if (!string.IsNullOrWhiteSpace(frameDefinition.Description))
                {
                    sb.AppendLine("/// <summary>");
                    sb.AppendLine($"/// {frameDefinition.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                    if (!string.IsNullOrWhiteSpace(frameDefinition.Value))
                    {
                        sb.AppendLine($"/// Frame value: {frameDefinition.Value}");
                    }
                    sb.AppendLine("/// </summary>");
                }

                // Generate class declaration inheriting from EzspFrameRequest
                string className = Sanitize.FunctionName(frameDefinition.CommandName) + "Request";
                sb.AppendLine($"public class {className} : EzspFrameRequestV8Plus");
                sb.AppendLine("{");

                // Generate properties for command arguments
                if (frameDefinition.CommandArguments != null && frameDefinition.CommandArguments.Count > 0)
                {
                    foreach (var arg in frameDefinition.CommandArguments)
                    {
                        if (!string.IsNullOrWhiteSpace(arg.Description))
                        {
                            sb.AppendLine("    /// <summary>");
                            sb.AppendLine($"    /// {arg.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                            sb.AppendLine("    /// </summary>");
                        }

                        // Check if the field name contains array notation (e.g., fieldName[SIZE])
                        int typeBracketIndex = arg.Type?.IndexOf('[') ?? -1;
                        if (typeBracketIndex >= 0)
                        {
                            // Extract field name and array size from name
                            string fieldArrayType = arg.Type![..typeBracketIndex];
                            string arrayPart = arg.Type[typeBracketIndex..];
                            string arraySize = arrayPart.Trim('[', ']');
                            TypeMapping? csharpBaseType = _typeMapper.GetTypeMapping(fieldArrayType);

                            // Check if array size is numeric (compile-time constant)
                            if (int.TryParse(arraySize, out _))
                            {
                                sb.AppendLine($"\tpublic {csharpBaseType?.CSharpType.Name}[] {arg.Name};");
                            }
                            else
                            {
                                // Array size is a symbolic constant 
                                sb.AppendLine($"\t// Array field with symbolic size: {arraySize}");
                                sb.AppendLine($"\tpublic {csharpBaseType?.CSharpType.Name}[] {arg.Name};");
                            }
                        }
                        else
                        {
                            TypeMapping? typeMapping = _typeMapper.GetTypeMapping(arg.Type);
                            if (typeMapping?.CSharpType.IsArray == true)
                            {
                                sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {typeMapping?.CSharpType.ArrayLength})]");
                                sb.AppendLine($"\tpublic {typeMapping?.CSharpType.Name}[] {arg.Name};");
                            }
                            else
                            {
                                sb.AppendLine($"\tpublic {typeMapping?.CSharpType.Name} {arg.Name} {{ get; set; }}");
                            }
                            
                            sb.AppendLine();
                        }
                    }
                }

                sb.AppendLine("}");

                _logger.LogDebug("Generated request class {commandName} with {argCount} arguments",
                    className, frameDefinition.CommandArguments?.Count ?? 0);

                _fileService.SaveFrameFile(sectionName, className, sb.ToString());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing frame definition for request {commandName}",
                    frameDefinition?.CommandName ?? "unknown");
                
            }
        }

        /// <summary>
        /// Processes a frame definition and generates C# response class code.
        /// </summary>
        /// <param name="_logger">Logger instance for diagnostic output.</param>
        /// <param name="sectionName">The section name (used for namespace generation).</param>
        /// <param name="frameDefinition">The frame definition to process.</param>
        /// <returns>Generated C# response class code as a string.</returns>
        internal void ProcessFrameDefinitionForResponse(string sectionName, FrameDefinition frameDefinition)
        {
            try
            {
                if (frameDefinition == null)
                {
                    _logger.LogWarning("Frame definition is null");
                }

                if (string.IsNullOrWhiteSpace(frameDefinition.CommandName))
                {
                    _logger.LogWarning("Frame command name is empty");
                }
                string sanitizedSectionName = Sanitize.SectionName(sectionName);

                var sb = new StringBuilder();

                _cSharpLanguageService.GenerateAutoGeneratedHeader(sb);

                sb.AppendLine("using System;");
                sb.AppendLine("using System.Buffers.Binary;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;");
                sb.AppendLine("using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;");

                if (_typeMapper.SectionTypeMappingExists(sanitizedSectionName) == true)
                {
                    sb.AppendLine($"using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Types;");
                }
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine();

                // Generate namespace
                sb.AppendLine($"namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.{sanitizedSectionName}.Frames;");
                sb.AppendLine();

                // Generate XML documentation with frame value
                if (!string.IsNullOrWhiteSpace(frameDefinition.Description))
                {
                    sb.AppendLine("/// <summary>");
                    sb.AppendLine($"/// {frameDefinition.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                    if (!string.IsNullOrWhiteSpace(frameDefinition.Value))
                    {
                        sb.AppendLine($"/// Frame value: {frameDefinition.Value}");
                    }
                    sb.AppendLine("/// </summary>");
                }

                string className = Sanitize.FunctionName(frameDefinition.CommandName) + "Response";
                // Generate class declaration inheriting from EzspFrameResponse
                sb.AppendLine($"public class {className} : EzspFrameResponseV8Plus");
                sb.AppendLine("{");

                // Generate properties for response arguments
                if (frameDefinition.ResponseArguments != null && frameDefinition.ResponseArguments.Count > 0)
                {
                    foreach (var arg in frameDefinition.ResponseArguments)
                    {
                        if (!string.IsNullOrWhiteSpace(arg.Description))
                        {
                            sb.AppendLine("    /// <summary>");
                            sb.AppendLine($"    /// {arg.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                            sb.AppendLine("    /// </summary>");
                        }

                        // Check if the field name contains array notation (e.g., fieldName[SIZE])
                        int typeBracketIndex = arg.Type?.IndexOf('[') ?? -1;
                        if (typeBracketIndex >= 0)
                        {
                            // Extract field name and array size from name
                            string fieldArrayType = arg.Type![..typeBracketIndex];
                            string arrayPart = arg.Type[typeBracketIndex..];
                            string arraySize = arrayPart.Trim('[', ']');
                            TypeMapping? csharpBaseType = _typeMapper.GetTypeMapping(fieldArrayType);

                            //if (Char.IsDigit(santizedTypeName[0]) == true)
                            //{
                            //    santizedTypeName = "_" + santizedTypeName;
                            //}

                            // Check if array size is numeric (compile-time constant)
                            if (int.TryParse(arraySize, out _))
                            {
                                sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {arraySize})]");
                                sb.AppendLine($"\tpublic {csharpBaseType?.CSharpType.Name}[] {Sanitize.PropertyName(arg.Name)};");
                            }
                            else
                            {
                                // Array size is a symbolic constant 
                                sb.AppendLine($"\t// Array field with symbolic size: {arraySize}");
                                if (frameDefinition.ResponseArguments.Any(a => a.Name == arraySize) == true)
                                {
                                    //_logger.LogWarning("Symbolic array size {arraySize} for argument {argName} in frame {commandName} does not match any other argument names", arraySize, arg.Name, frameDefinition.CommandName);
                                }
                                else if (string.IsNullOrEmpty(MapCConstants.MapConstant(arraySize)) == false)
                                {
                                    sb.AppendLine($"\t[MarshalAs(UnmanagedType.ByValArray, SizeConst = {MapCConstants.MapConstant(arraySize)})]");
                                }
                                sb.AppendLine($"\tpublic {csharpBaseType?.CSharpType.Name}[] {Sanitize.PropertyName(arg.Name)};");
                            }
                        }
                        else
                        {
                            TypeMapping? csharpBaseType = _typeMapper.GetTypeMapping(arg.Type);
                            sb.AppendLine($"\tpublic {csharpBaseType?.CSharpType.Name} {Sanitize.PropertyName(arg.Name)} {{ get; set; }}");
                            sb.AppendLine();
                        }
                    }
                }

                sb.AppendLine($"\tpublic static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)");
                sb.AppendLine("\t{");
                sb.AppendLine($"\t\t{className} frame = new {className}();");
                sb.AppendLine($"\t\tint index = frame.ParseHeader(frameBytes);");
                sb.AppendLine();
                if (frameDefinition.ResponseArguments != null && frameDefinition.ResponseArguments.Count > 0)
                {
                    int frameBytesPosition = 0;
                    foreach (FrameArgument arg in frameDefinition.ResponseArguments)
                    {
                        //if (!string.IsNullOrWhiteSpace(arg.Description))
                        //{
                        //    sb.AppendLine("    /// <summary>");
                        //    sb.AppendLine($"    /// {arg.Description.XmlEscape().AddXmlCommentPrefixAfterLineBreak(1)}");
                        //    sb.AppendLine("    /// </summary>");
                        //}

                        sb.Append($"\t\tframe.{Sanitize.PropertyName(arg.Name)} = ");

                        TypeMapping? typeMapping = null;
                        if (arg.Type.IsArrayTypeDefinition() == true)
                        {
                            typeMapping = _typeMapper.GetTypeMapping(arg.Type.GetArrayDefinitionBaseType());
                            if (typeMapping == null)
                            {
                                _logger.LogError("No type mapping found for array base type {argType} in frame {commandName}", arg.Type.GetArrayDefinitionBaseType(), frameDefinition.CommandName);
                                sb.AppendLine($"\t\t// Unknown type mapping for array base type {arg.Type.GetArrayDefinitionBaseType()} of argument {arg.Name} in frame {frameDefinition.CommandName}");
                                //return string.Empty;
                            }
                            int arraySize = arg.Type.GetArrayDefinitionSize();
                            string arrayLengthSymbolicSize = string.Empty;

                            // if we have a symbolic size, try to map it to a constant
                            if (arraySize == -1)
                            {
                                arrayLengthSymbolicSize = arg.Type.GetArrayDefinitionSymbolicSize();
                                if (string.IsNullOrEmpty(MapCConstants.MapConstant(arrayLengthSymbolicSize)) == false)
                                {
                                    arraySize = int.Parse(MapCConstants.MapConstant(arrayLengthSymbolicSize));
                                }
                            }


                            bool isVariableLengthArray = (arraySize == -1);

                            // todo incomplete - need code for different primitives.
                            //                    public static class SpanExtensions
                            //{
                            //    public static T[] ToArray<T>(this ReadOnlySpan<T> span)
                            //    {
                            //        var array = new T[span.Length];
                            //        span.CopyTo(array);
                            //        return array;
                            //    }
                            //}

                            //ReadOnlySpan<byte> bytes = stackalloc byte[16];
                            //                    // reinterpret as ints
                            //                    ReadOnlySpan<int> ints = MemoryMarshal.Cast<byte, int>(bytes);
                            //                    int[] arr = ints.ToArray();  // using the extension above

                            if (typeMapping?.CSharpType.Name == "byte" && isVariableLengthArray == true)
                            {
                                sb.AppendLine($"frameBytes.Slice(index, frame.{Sanitize.PropertyName(arrayLengthSymbolicSize)}).ToArray();");
                                sb.AppendLine($"\t\tindex += frame.{Sanitize.PropertyName(arrayLengthSymbolicSize)};");
                            }
                            else if (isVariableLengthArray == true)
                            {
                                //sb.AppendLine($"MemoryMarshal.Cast<byte, {typeMapping?.CSharpType.Name}>(frameBytes.Slice(index, {Char.ToUpper(arrayLengthSymbolicSize[0])}{arrayLengthSymbolicSize[1..]})).ToArray();");
                                //sb.AppendLine($"\t\tindex += {typeMapping?.CType.SizeInBytes * arraySize};");
                            }
                            else
                            {
                                sb.AppendLine($"MemoryMarshal.Cast<byte, {typeMapping?.CSharpType.Name}>(frameBytes.Slice(index, {typeMapping?.CType.SizeInBytes * arraySize})).ToArray();");
                                sb.AppendLine($"\t\tindex += {typeMapping?.CType.SizeInBytes * arraySize};");
                            }
                            //if (isVariableLengthArray == true)
                            //{
                            //    sb.AppendLine($"frameBytes.Slice(index, {typeMapping?.CType.SizeInBytes} * {Char.ToUpper(arrayLengthSymbolicSize[0])}{arrayLengthSymbolicSize[1..]})");
                            //}
                            //else
                            //{
                            //    sb.AppendLine($"MemoryMarshal.Cast<byte, {typeMapping?.CSharpType.Name}>(frameBytes.Slice(index, {typeMapping?.CType.SizeInBytes * arraySize})).ToArray();");
                            //}


                        }
                        else
                        {
                            typeMapping = _typeMapper.GetTypeMapping(arg.Type);

                            if (typeMapping != null)
                            {


                                if (typeMapping?.CType.IsEnum == true)
                                {
                                    TypeMapping baseTypeMapping = _typeMapper.GetTypeMapping(typeMapping?.CType.UnderlyingTypeName ?? "") ?? throw new InvalidOperationException($"No type mapping found for underlying type {typeMapping?.CType.UnderlyingTypeName} of enum {typeMapping?.CType.Name}");
                                    sb.Append($"({typeMapping?.CSharpType.Name})");
                                    sb.AppendLine(ReadPrimitiveTypeString(baseTypeMapping.CType.Name));
                                }
                                else if (typeMapping?.CType.IsStruct == true)
                                {
                                    if (typeMapping?.CType.IsVariableLengthStruct == true)
                                    {
                                        //sb.AppendLine($"{typeMapping?.CSharpType.Name}.Parse(frameBytes.Slice(index, frameBytes.Length - index));");
                                        sb.AppendLine("Hello fix this");
                                        _logger.LogError("Variable length struct parsing not implemented for argument {argName} of type {argType} in frame {commandName}", arg.Name, arg.Type, frameDefinition.CommandName);
                                    }
                                    else
                                    {
                                        sb.AppendLine($"MemoryMarshal.Read<{typeMapping?.CSharpType.Name}>(frameBytes.Slice(index, {typeMapping?.CType.SizeInBytes}));");
                                    }
                                }
                                else
                                {
                                    sb.AppendLine(ReadPrimitiveTypeString(typeMapping.Value.CSharpType.Name));
                                }
                            }
                            else
                            {
                                _logger.LogError("No type mapping found for argument {argName} of type {argType} in frame {commandName}", arg.Name, arg.Type, frameDefinition.CommandName);
                                sb.AppendLine($"\t\t// Unknown type mapping for argument {arg.Name} of type {arg.Type}");
                                //return string.Empty;
                            }

                            sb.AppendLine($"\t\tindex += {typeMapping?.CType.SizeInBytes};");

                            frameBytesPosition += typeMapping?.CType.SizeInBytes ?? 0;
                        }

                    }
                }


                sb.AppendLine();
                sb.AppendLine($"\t\treturn frame;");
                sb.AppendLine("\t}");

                sb.AppendLine("}");

                _logger.LogDebug("Generated response class {commandName} with {argCount} arguments",
                    className, frameDefinition.ResponseArguments?.Count ?? 0);

                _fileService.SaveFrameFile(sectionName, className, sb.ToString());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing frame definition for response {commandName}",
                    frameDefinition?.CommandName ?? "unknown");
            }
        }

        private string ReadPrimitiveTypeString(string cPrimitveName)
        {
            return cPrimitveName switch
            {
                "int32_t" => "BinaryPrimitives.ReadInt32LittleEndian(frameBytes.Slice(index, 4));",
                "uint32_t" => "BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));",
                "int16_t" => "BinaryPrimitives.ReadInt16LittleEndian(frameBytes.Slice(index, 2));",
                "uint16_t" => "BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));",
                "int64_t" => "BinaryPrimitives.ReadInt64LittleEndian(frameBytes.Slice(index, 8));",
                "uint64_t" => "BinaryPrimitives.ReadUInt64LittleEndian(frameBytes.Slice(index, 8));",
                "uint8_t" => "frameBytes[index];",
                "int8_t" => "(sbyte)frameBytes[index];",
                "bool" => "((frameBytes[index] & 1) == 1);",
                "int" => "BinaryPrimitives.ReadInt32LittleEndian(frameBytes.Slice(index, 4));",
                "uint" => "BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));",
                "short" => "BinaryPrimitives.ReadInt16LittleEndian(frameBytes.Slice(index, 2));",
                "ushort" => "BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));",
                "long" => "BinaryPrimitives.ReadInt64LittleEndian(frameBytes.Slice(index, 8));",
                "ulong" => "BinaryPrimitives.ReadUInt64LittleEndian(frameBytes.Slice(index, 8));",
                "byte" => "frameBytes[index];",
                "sbyte" => "(sbyte)frameBytes[index];",
                _ => throw new Exception($"Not a primitive type: {cPrimitveName}"),
            };
        }


    }
}
