//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.TokenInterface.Frames;

/// <summary>
/// Factory reset all configured zigbee tokens
/// Frame value: 0x0077
/// </summary>
public class TokenFactoryResetResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		TokenFactoryResetResponse frame = new TokenFactoryResetResponse();
	}
}
}
