//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// This function clears the key table of the current network.
/// Frame value: 0x00B1
/// </summary>
public class ClearKeyTableResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The success or failure of the operation.
    /// </summary>
    public sl_status_t status { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		ClearKeyTableResponse frame = new ClearKeyTableResponse();
		frame.status = 	}
}
}
