//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// Import an application link key into the key table.
/// Frame value: 0x010E
/// </summary>
public class SecManImportLinkKeyResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Status of key import operation.
    /// </summary>
    public sl_status_t Status { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		SecManImportLinkKeyResponse frame = new SecManImportLinkKeyResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;

		return frame;
	}
}
