//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Security.Frames;

/// <summary>
/// This function sends an APS TransportKey command containing the current trust center link key. The node to which the command is sent is specified via the short and long address arguments.
/// Frame value: 0x0067
/// </summary>
public class SendTrustCenterLinkKeyResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// An sl_status_t value indicating success of failure of the operation
    /// </summary>
    public sl_status_t status { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		SendTrustCenterLinkKeyResponse frame = new SendTrustCenterLinkKeyResponse();
		frame.status = 	}
}
}
