#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Bootloader.Frames;

/// <summary>
/// A callback invoked by the EmberZNet stack when a bootload message is received.
/// Frame value: 0x0092
/// </summary>
public class IncomingBootloadMessageHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The EUI64 of the sending node.
    /// </summary>
    public byte Longid { get; set; }

    /// <summary>
    /// Information about the incoming packet.
    /// </summary>
    public ZigbeeRxPacketInfo Packetinfo { get; set; }

    /// <summary>
    /// The length of the &lt;i&gt;messageContents&lt;/i&gt; parameter in bytes.
    /// </summary>
    public byte Messagelength { get; set; }

    /// <summary>
    /// The bootload message that was sent.
    /// </summary>
	// Array field with symbolic size: messageLength
	public byte[] messageContents;
	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		IncomingBootloadMessageHandlerResponse frame = new IncomingBootloadMessageHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Longid = frameBytes[index];
		index += 1;
		frame.Packetinfo = /* TODO: Implement parsing for type sl_zigbee_rx_packet_info_t */ null;
		index += 0;
		frame.Messagelength = frameBytes[index];
		index += 1;
		frame.Messagecontents = /* TODO: Implement parsing for type uint8_t[messageLength] */ null;
		index += 0;

		return frame;
	}
}

#endif