#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Frames;

/// <summary>
/// Update the GP Proxy table based on a GP pairing.
/// Frame value: 0x00C9
/// </summary>
public class GpProxyTableProcessGpPairingRequest : EzspFrameRequestV8Plus
{
	/// <summary>
	/// The frameId of the frame
	/// </summary>
	public static ushort FrameId { get { return 0x00C9; } }

    /// <summary>
    /// The options field of the GP Pairing command.
    /// </summary>
	public uint Options { get; set; }

    /// <summary>
    /// The target GPD.
    /// </summary>
	public ZigbeeGpAddress Addr { get; set; }

    /// <summary>
    /// The communication mode of the GP Sink.
    /// </summary>
	public byte CommMode { get; set; }

    /// <summary>
    /// The network address of the GP Sink.
    /// </summary>
	public ushort SinkNetworkAddress { get; set; }

    /// <summary>
    /// The group ID of the GP Sink.
    /// </summary>
	public ushort SinkGroupId { get; set; }

    /// <summary>
    /// The alias assigned to the GPD.
    /// </summary>
	public ushort AssignedAlias { get; set; }

    /// <summary>
    /// The IEEE address of the GP Sink.
    /// </summary>
	public byte[] SinkIeeeAddress;
    /// <summary>
    /// The key to use for the target GPD.
    /// </summary>
	public ZigbeeKeyData GpdKey { get; set; }

    /// <summary>
    /// The GPD security frame counter.
    /// </summary>
	public uint GpdSecurityFrameCounter { get; set; }

    /// <summary>
    /// The forwarding radius.
    /// </summary>
	public byte ForwardingRadius { get; set; }

}

#endif