#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.GreenPower.Frames;

/// <summary>
/// Clears all entries within the translation table.
/// Frame value: 0x010B
/// </summary>
public class GpTranslationTableClearResponse : EzspFrameResponseV8Plus
{
	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GpTranslationTableClearResponse frame = new GpTranslationTableClearResponse();
		int index = frame.ParseHeader(frameBytes);


		return frame;
	}
}

#endif