#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


/// <summary>
/// Data associated with the ZLL security algorithm.
/// </summary>

using System;
using System.Runtime.InteropServices;
using ZigbeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

[StructLayout(LayoutKind.Sequential)]
public struct ZigbeeZllSecurityAlgorithmData
{
	/// <summary>
	/// Transaction identifier.
	/// </summary>
	public uint transactionId;

	/// <summary>
	/// Response identifier.
	/// </summary>
	public uint responseId;

	/// <summary>
	/// Bitmask.
	/// </summary>
	public ushort bitmask;

}


#endif