#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


/// <summary>
/// The parameters of a ZLL network.
/// </summary>

using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

[StructLayout(LayoutKind.Sequential)]
public struct ZigbeeZllNetwork
{
	/// <summary>
	/// The parameters of a ZigBee network.
	/// </summary>
	public Zigbeezigbeenetwork zigbeeNetwork;

	/// <summary>
	/// Data associated with the ZLL security algorithm.
	/// </summary>
	public Zigbeezllsecurityalgorithmdata securityAlgorithm;

	/// <summary>
	/// Associated EUI64.
	/// </summary>
	[MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
	public _802154longaddr[] eui64;

	/// <summary>
	/// The node id.
	/// </summary>
	public ushort nodeId;

	/// <summary>
	/// The ZLL state.
	/// </summary>
	public Zigbeezllstate state;

	/// <summary>
	/// The node type.
	/// </summary>
	public Zigbeenodetype nodeType;

	/// <summary>
	/// The number of sub devices.
	/// </summary>
	public byte numberSubDevices;

	/// <summary>
	/// The total number of group identifiers.
	/// </summary>
	public byte totalGroupIdentifiers;

	/// <summary>
	/// RSSI correction value.
	/// </summary>
	public byte rssiCorrection;

}


#endif