#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


/// <summary>
/// ZLL address assignment data.
/// </summary>

using System;
using System.Runtime.InteropServices;
using ZigbeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

[StructLayout(LayoutKind.Sequential)]
public struct ZigbeeZllAddressAssignment
{
	/// <summary>
	/// Relevant node id.
	/// </summary>
	public ushort nodeId;

	/// <summary>
	/// Minimum free node id.
	/// </summary>
	public ushort freeNodeIdMin;

	/// <summary>
	/// Maximum free node id.
	/// </summary>
	public ushort freeNodeIdMax;

	/// <summary>
	/// Minimum group id.
	/// </summary>
	public ushort groupIdMin;

	/// <summary>
	/// Maximum group id.
	/// </summary>
	public ushort groupIdMax;

	/// <summary>
	/// Minimum free group id.
	/// </summary>
	public ushort freeGroupIdMin;

	/// <summary>
	/// Maximum free group id.
	/// </summary>
	public ushort freeGroupIdMax;

}


#endif