#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.CertificateBasedKeyExchangeCBKE.Frames;

/// <summary>
/// The handler that returns the results of the signing operation. On success, the signature will be appended to the original message (including the signature type indicator that replaced the startIndex field for the signing) and both are returned via this callback.
/// Frame value: 0x00A7
/// </summary>
public class DsaSignHandlerResponse : EzspFrameResponseV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x00A7; } }

    /// <summary>
    /// The result of the DSA signing operation.
    /// </summary>
	public Status Status { get; set; }

    /// <summary>
    /// The length of the &lt;i&gt;messageContents&lt;/i&gt; parameter in bytes.
    /// </summary>
	public byte MessageLength { get; set; }

    /// <summary>
    /// The message and attached which includes the original message and the appended signature.
    /// </summary>
	// Array field with symbolic size: messageLength
	public byte[] MessageContents;
	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		DsaSignHandlerResponse frame = new DsaSignHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = (Status)BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
		index += 4;
		frame.MessageLength = frameBytes[index];
		index += 1;
		frame.MessageContents = frameBytes.Slice(index, frame.MessageLength).ToArray();
		index += frame.MessageLength;

		return frame;
	}
}

#endif