#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// This call is fired when a counter exceeds its threshold
/// Frame value: 0x00F2
/// </summary>
public class CounterRolloverHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Type of Counter
    /// </summary>
    public sl_zigbee_counter_type_t Type { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		CounterRolloverHandlerResponse frame = new CounterRolloverHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Type = /* TODO: Implement parsing for type sl_zigbee_counter_type_t */ null;
		index += 0;

		return frame;
	}
}

#endif