#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Check if a particular counter can report on the destination node ID they have been triggered from.
/// Frame value: 0x0133
/// </summary>
public class CounterRequiresDestinationNodeIdResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Whether this counter requires the destination node ID.
    /// </summary>
    public bool Requires { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		CounterRequiresDestinationNodeIdResponse frame = new CounterRequiresDestinationNodeIdResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Requires = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif