#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;
/// <summary>
/// This call is fired when a counter exceeds its threshold
/// Frame value: 0x00F2
/// </summary>
public class CounterRolloverHandlerResponse : EzspFrameResponseV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x00F2; }
    /// <summary>
    /// Type of Counter
    /// </summary>
    public ZigbeeCounterType Type { get; set; }

    public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
    {
        EmberResponseHeader header = EzspFrameResponseV8Plus.ParseHeader(frameBytes);
        CounterRolloverHandlerResponse frame = new CounterRolloverHandlerResponse();
        int index = Constants.EmberFrameHeaderLength;
        frame.Type = (ZigbeeCounterType)frameBytes[index];
        index += 1;
        return frame;
    }
}
#endif