#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// A callback indicating a custom EZSP message has been received.
/// Frame value: 0x0054
/// </summary>
public class CustomFrameHandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The length of the custom frame payload.
    /// </summary>
    public byte Payloadlength { get; set; }

    /// <summary>
    /// The payload of the custom frame.
    /// </summary>
    public uint8_t[payloadLength] Payload { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		CustomFrameHandlerResponse frame = new CustomFrameHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Payloadlength = frameBytes[index];
		index += 1;
		frame.Payload = /* TODO: Implement parsing for type uint8_t[payloadLength] */ null;
		index += 0;

		return frame;
	}
}

#endif