#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// A callback indicating a custom EZSP message has been received.
/// Frame value: 0x0054
/// </summary>
public class CustomFrameHandlerResponse : EzspFrameResponseV8Plus
{
	/// <summary>
	/// The frameId of the frame
]	/// </summary>
	public static ushort FrameId { get { return 0x0054; } }

    /// <summary>
    /// The length of the custom frame payload.
    /// </summary>
	public byte PayloadLength { get; set; }

    /// <summary>
    /// The payload of the custom frame.
    /// </summary>
	// Array field with symbolic size: payloadLength
	public byte[] Payload;
	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		CustomFrameHandlerResponse frame = new CustomFrameHandlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.PayloadLength = frameBytes[index];
		index += 1;
		frame.Payload = frameBytes.Slice(index, frame.PayloadLength).ToArray();
		index += frame.PayloadLength;

		return frame;
	}
}

#endif