#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;
/// <summary>
/// Retrieves a manufacturing token from the Flash Information Area of the NCP (except for SL_ZIGBEE_EZSP_STACK_CAL_DATA which is managed by the stack).
/// Frame value: 0x000B
/// </summary>
public class GetMfgTokenRequest : EzspFrameRequestV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x000B; }
    /// <summary>
    /// Which manufacturing token to read.
    /// </summary>
    public ZigbeeEzspMfgTokenId TokenId { get; set; }

    /// <summary>
    /// Creates the parameters for this frame
    /// </summary>
    /// <returns>The frame parameters as a byte array</returns>
    protected override byte[] CreateParameters()
    {
        return new byte[]
        {
        };
    }
}
#endif