#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Returns a pseudorandom number.
/// Frame value: 0x0049
/// </summary>
public class GetRandomNumberResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// Always returns SL_STATUS_OK.
    /// </summary>
    public Status Status { get; set; }

    /// <summary>
    /// A pseudorandom number.
    /// </summary>
    public ushort Value { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetRandomNumberResponse frame = new GetRandomNumberResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = (Status)BinaryPrimitives.ReadUInt32LittleEndian(frameBytes.Slice(index, 4));
		index += 4;
		frame.Value = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;

		return frame;
	}
}

#endif