#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Allows the HOST to know whether the NCP is running the XNCP library. If so, the response contains also the manufacturer ID and the version number of the XNCP application that is running on the NCP.
/// Frame value: 0x0013
/// </summary>
public class GetXncpInfoResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// SL_STATUS_OK if the NCP is running the XNCP library. SL_STATUS_INVALID_STATE otherwise.
    /// </summary>
    public sl_status_t Status { get; set; }

    /// <summary>
    /// The manufactured ID the user has defined in the XNCP application.
    /// </summary>
    public ushort Manufacturerid { get; set; }

    /// <summary>
    /// The version number of the XNCP application.
    /// </summary>
    public ushort Versionnumber { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		GetXncpInfoResponse frame = new GetXncpInfoResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Status = /* TODO: Implement parsing for type sl_status_t */ null;
		index += 0;
		frame.Manufacturerid = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;
		frame.Versionnumber = BinaryPrimitives.ReadUInt16LittleEndian(frameBytes.Slice(index, 2));
		index += 2;

		return frame;
	}
}

#endif