#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// Indicates that the NCP received an invalid command.
/// Frame value: 0x0058
/// </summary>
public class InvalidCommandResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The reason why the command was invalid.
    /// </summary>
    public sl_zigbee_ezsp_status_t Reason { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		InvalidCommandResponse frame = new InvalidCommandResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.Reason = /* TODO: Implement parsing for type sl_zigbee_ezsp_status_t */ null;
		index += 0;

		return frame;
	}
}

#endif