#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;
using System.Runtime.InteropServices;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;

/// <summary>
/// This call is fired when mux detects an invalid rx case, which would be different rx channels for different protocol contexts, when fast cahnnel switching is not enabled
/// Frame value: 0x0062
/// </summary>
public class Mux_invalid_rx_handlerResponse : EzspFrameResponseV8Plus
{
	public byte NewRxChannel { get; set; }

	public byte OldRxChannel { get; set; }

	public static EzspFrameResponseV8Plus Parse(ReadOnlySpan<byte> frameBytes)
	{
		Mux_invalid_rx_handlerResponse frame = new Mux_invalid_rx_handlerResponse();
		int index = frame.ParseHeader(frameBytes);

		frame.NewRxChannel = frameBytes[index];
		index += 1;
		frame.OldRxChannel = frameBytes[index];
		index += 1;

		return frame;
	}
}

#endif