#if VERSION_2025_6_2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Enumerations;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Common.Types;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.Utilities.Frames;
/// <summary>
/// Extend a joiner&apos;s timeout to wait for the network key on the joiner default key timeout is 3 sec, and only values greater equal to 3 sec are accepted.
/// Frame value: 0x003A
/// </summary>
public class SetupDelayedJoinRequest : EzspFrameRequestV8Plus, IFrameIdentifier
{
    /// <summary>
    /// The frameId of the frame
    /// </summary>
    public static ushort FrameId { get => 0x003A; }
    /// <summary>
    /// Network key timeout
    /// </summary>
    public byte NetworkKeyTimeoutS { get; set; }

    /// <summary>
    /// Creates the parameters for this frame
    /// </summary>
    /// <returns>The frame parameters as a byte array</returns>
    protected override byte[] CreateParameters()
    {
        return new byte[]
        {
        };
    }
}
#endif