//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.CertificateBasedKeyExchangeCBKE.Frames;

/// <summary>
/// Verify that signature of the associated message digest was signed by the private key of the associated certificate.
/// Frame value: 0x00B0
/// </summary>
public class DsaVerify283k1Response : EzspFrameResponseV8Plus
{
    public sl_status_t status { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		DsaVerify283k1Response frame = new DsaVerify283k1Response();
		frame.status = 	}
}
}
