//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.CertificateBasedKeyExchangeCBKE.Frames;

/// <summary>
/// A callback by the Crypto Engine indicating that a new 283k1 ephemeral public/private key pair has been generated. The public/private key pair is stored on the NCP, but only the associated public key is returned to the host. The node&apos;s associated certificate is also returned.
/// Frame value: 0x00E9
/// </summary>
public class GenerateCbkeKeys283k1HandlerResponse : EzspFrameResponseV8Plus
{
    /// <summary>
    /// The result of the CBKE operation.
    /// </summary>
    public sl_status_t status { get; set; }

    /// <summary>
    /// The generated ephemeral public key.
    /// </summary>
    public sl_zigbee_public_key_283k1_data_t ephemeralPublicKey { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GenerateCbkeKeys283k1HandlerResponse frame = new GenerateCbkeKeys283k1HandlerResponse();
		frame.status = 		frame.ephemeralPublicKey = 	}
}
}
