//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ZigBeeNet.Hardware.EmberV8Plus.Ezsp;

namespace ZigBeeNet.Hardware.EmberV8Plus.Ezsp.CertificateBasedKeyExchangeCBKE.Frames;

/// <summary>
/// Retrieves the certificate installed on the NCP.
/// Frame value: 0x00A5
/// </summary>
public class GetCertificateResponse : EzspFrameResponseV8Plus
{
    public sl_status_t status { get; set; }

    /// <summary>
    /// The locally installed certificate.
    /// </summary>
    public sl_zigbee_certificate_data_t localCert { get; set; }

	public static EzspFrameResponseV8Plus Parse(byte[] frameBytes)
	{
		GetCertificateResponse frame = new GetCertificateResponse();
		frame.status = 		frame.localCert = 	}
}
}
